### ISSUE TITLE
think-swoole 2.0.17能无缝升级到最新版本吗

### ISSUE THREAD

**Issue by yunxi177** [top-think/think-swoole#105]
使用TP5.1框架,目前think-swoole是 2.0.17 目前遇到的问题是在onOpen和OnMessage 事件中使用db和model 进行查询,经常性出现数据库连接占满问题(经过排查是因为在回调事件中使用过的db 和 model 的连接不会被释放),看最新版已经有db连接池,因此想了解一下,能不能直接升级到最新的版本,以解决我目前所遇到的问题

**Comment by liu21st** [comment]
并不能的，3.0版本是针对ThinkPHP6.0设计的
