### ISSUE TITLE
swoole 模式下，Request::param 无法获取到 application/json 类型的数据

### ISSUE THREAD

**Issue by kingzcheung** [top-think/think-swoole#108]
无论是验证器还是控制器都获取不到通过application/json  传进来的json数据

感觉这里传入Request 对象没有效果？

https://github.com/top-think/think-swoole/blob/9c623cd88424a0ddbc3aaac96d7c3b30c932a69d/src/concerns/InteractsWithHttp.php#L95

**Comment by kingzcheung** [comment]
通过以下两个方法能获取到原始的json数据：

$request->getContent();
$request->getInput();

**Comment by yunwuxin** [comment]
这个已经修正过了
