### ISSUE TITLE
rpc dispatcher 中没有任何可以触发的事件，可以考虑加上吗？

### ISSUE THREAD

**Issue by suframe** [top-think/think-swoole#112]
rpc dispatcher 里面invoke 获取结果后，直接就send了，之间没有可以监听的地方， 比如http完了后有httpEnd,  希望加上一个监听事件，用于其他业务处理

顺便提下，能否应用直接rpc通信的时候，可以设置一个request_id.方便链路追踪

**Comment by yunwuxin** [comment]
这个很好实现的  自定义parser就可以了 
配置是这个 
![image](https://user-images.githubusercontent.com/2168125/87655843-4f1e7880-c78b-11ea-846c-061a3c46963a.png)
默认使用的内置的JsonParser
