### ISSUE TITLE
输出大数据量的json偶发无响应

### ISSUE THREAD

**Issue by k155** [top-think/think-swoole#113]
使用tp6+swoole来写接口，接口输出的json数据量很大时，保存到文件里大小有100k，接口偶发无响应，状态码是200，但没有任何返回，查看 think-swoole的日志，提示如下
`WARNING swFactoryProcess_finish(:472): sendto to reactor failed, Error: No buffer space available[105]
`
调大了扩展的config/swoole.php配置文件里 'socket_buffer_size'    => 128 * 1024 * 1024,也没用

think-swoole扩展版本是 V3.0.2

swoole信息
`
swoole

Swoole => enabled
Author => Swoole Team <team@swoole.com>
Version => 4.3.6
Built => Jul 19 2019 11:12:13
coroutine => enabled
epoll => enabled
eventfd => enabled
signalfd => enabled
cpu_affinity => enabled
spinlock => enabled
rwlock => enabled
sockets => enabled
http2 => enabled
pcre => enabled
zlib => enabled
mutex_timedlock => enabled
pthread_barrier => enabled
futex => enabled
async_redis => enabled

Directive => Local Value => Master Value
swoole.enable_coroutine => On => On
swoole.display_errors => On => On
swoole.use_shortname => On => On
swoole.unixsock_buffer_size => 8388608 => 8388608
`

还有什么好的处理方法吗

**Comment by yunwuxin** [comment]
什么系统 mac吗

**Comment by k155** [comment]
是 centos 系统

**Comment by yunwuxin** [comment]
你升级下swoole看看

**Comment by k155** [comment]
swoole升级，扩展 think-swoole 需要升级吗，升级需要注意什么没，因为已经在运行了，部分线上用户分配到这台服务器

**Comment by xavieryang007** [comment]
http模式还是websocket

**Comment by k155** [comment]
http模式的，tp框架传统接口开发

**Comment by xavieryang007** [comment]
buffer_output_size    
```
$server->set([
    'buffer_output_size' => 32 * 1024 *1024, //必须为数字
])

```    

    单位为字节，默认为2M，如设置32 * 1024 *1024表示，单次Server->send最大允许发送32M字节的数据    

    调用Server->send， Http\Server->end/write，WebSocket\Server->push 等发送数据指令时，单次最大发送的数据不得超过buffer_output_size配置。

**Comment by k155** [comment]
目前我的配置是  'buffer_output_size'    => 10 * 1024 * 1024,

**Comment by k155** [comment]
建议调大一点是吧

**Comment by yunwuxin** [comment]
改进了下  大数据量的时候采用分段发送了
