### ISSUE TITLE
2.0版本还有支持https的计划吗？

### ISSUE THREAD

**Issue by weijianghu** [top-think/think-swoole#114]
2.0版本还有支持https的计划吗？

**Comment by yunwuxin** [comment]
2.0不再更新了

**Comment by xavieryang007** [comment]
nginx 前面做代理就可以支持HTTPS了

**Comment by weijianghu** [comment]
https://github.com/top-think/think-swoole/blob/c0e227c0f9b400cd1e8524d4cc22039d715a26e2/src/Http.php#L57

https://github.com/top-think/think-swoole/blob/c0e227c0f9b400cd1e8524d4cc22039d715a26e2/src/Http.php#L60 
$sockType这个传入变量没有用到，导致不支持https，现在直接在代码中改掉了 ，让其支持https

**Comment by xavieryang007** [comment]
wss https .只需要在nginx配置，并装消息转发到swoole就可以了

**Comment by weijianghu** [comment]
嗯，nginx转发也可以，但是think-swoole2.0不支持就感觉有点不爽。。。。。。。
