### ISSUE TITLE
关于异步下DB连接池的报错与task的finish的监听

### ISSUE THREAD

**Issue by LonelySally** [top-think/think-swoole#120]
1.设置pool['db']['enable']=>true,max_active=3,max_wait_time=>5默认配置.
在某个api下使用swoole的异步go(function(){Event::trigger('doEvent')}).触发事件(**这个事件里有Db操作**).当访问3次接口后Borrow the connection timeout in 5.00(s), connections in pool: 0, all connections: 3.系统提示连接池被耗尽.异步里的Db连接没被释放.需要怎么处理?找了好久没看到解决办法.
2.设置监听
'swoole.task'=>[\app\listener\SwooleTask::class]
'swoole.finish'=>[\app\listener\SwooleTaskFinish::class]
在某个api下执行$server->task(['a'=>'b']);//(Swoole\Server $server)
在控制台下可以**看到SwooleTask的输出,看不到SwooleTaskFinish的输出**.要如何操作才能执行finish?

**Comment by zengsuyi** [comment]
2.设置监听
请问这个是在哪里设置？

**Comment by LonelySally** [comment]
> 2.设置监听
> 
> 请问这个是在哪里设置？

event.php
