### ISSUE TITLE
开启Http服务后多应用模式下路由无法正常读取配置文件

### ISSUE THREAD

**Issue by rorenx** [top-think/think-swoole#121]
![image](https://user-images.githubusercontent.com/54785213/74517114-8b377e00-4f4c-11ea-9b0a-6378cb1714bb.png)

框架大致目录如上
[错误场景]
代码在FPM下运行正常,当开始swoole的http服务时,首先访问admin应用的路由，可以正常访问，随之访问api应用的路由，进入了admin路由配置文件的miss路由,重启swoole http后将访问两个应用的顺序颠倒，先反正api后访问admin，api正常,访问admin时进入api的miss路由,随后尝试改成不同应用入口访问不用应用，效果也一样

[错误见解]
1.think-swoole是否对多应用的支持不够完善？
2.是否存在服务开启时仅加载首次路由配置文件，之后都只读取第一次的文件？
3.是否将当前场景误判为单应用场景

**Comment by rorenx** [comment]
补充一点，路由文件是放在根目录下的route文件夹中，两个应用有各自的文件夹,路由配置文件均为route.php
route
 --admin
     --route.php
 --api
     --route.php

**Comment by liu21st** [comment]
最新的多应用路由定义目录位置是在应用目录下的route目录

**Comment by rorenx** [comment]
> 最新的多应用路由定义目录位置是在应用目录下的route目录

按照文档给出的路由文件放在应用目录下的route目录中这种情况也试过了，也是相同情况的呢

**Comment by yunwuxin** [comment]
多应用就别试了  不适合这个扩展    这个扩展的Route和App对象是常驻内存的  而多应用需要根据不同的应用加载不同的路由和配置

**Comment by yunwuxin** [comment]
建议使用控制器分层结构  不要使用多应用

**Comment by 502647092** [comment]
@yunwuxin 多应用不考虑支持一下嘛

**Comment by qq475281441** [comment]
> @yunwuxin 多应用不考虑支持一下嘛

不知道手动加载所有路由进内存有没有效果，有时间可以试一下。

**Comment by etjson** [comment]
没有解决方案么？作者指导一下啊，这是劝退的节奏嘛。

**Comment by zhlhuang** [comment]
如果不考虑加载route 那么多应用是不是就可以用？
