### ISSUE TITLE
子进程中require_once返回ture

### ISSUE THREAD

**Issue by LCRONG** [top-think/think-swoole#123]
由于在think文件初始化应用时已经加载了文件，例如log.php，导致后续的子进程使用require_once返回true

**Comment by yunwuxin** [comment]
你想表达什么

**Comment by LCRONG** [comment]
就是在 WithApplication中的 prepareApplication方法为啥要重新new一个app呢?而不是直接服务已经存在的app呢？

**Comment by yunwuxin** [comment]
这两个app是不一样的
