### ISSUE TITLE
class not exists: swoole，尝试使用异步报错

### ISSUE THREAD

**Issue by xiuavier** [top-think/think-swoole#125]
tp5框架里面，使用think-swoole，然后尝试$swoole = app('swoole');这样子实现异步，但是报错了，网上搜索了一下感觉好像是说没有自动加载，但是我是用composer安装的，该如何解决这个问题呀

**Comment by xiuavier** [comment]
```
$swoole = app('swoole');
$swoole->task($taskData);
```

**Comment by xiuavier** [comment]
我是这么用的

**Comment by zengsuyi** [comment]
应该不是这么用  我也在查这个

**Comment by twomiao** [comment]
> ```
> $swoole = app('swoole');
> $swoole->task($taskData);
> ```

app('swoole.server') 或者 app(Server::class)->task(xxxx);

**Comment by twomiao** [comment]
> 应该不是这么用 我也在查这个

app('swoole.server') or app(Server::class)->task(xxxx);

**Comment by zengsuyi** [comment]
> > 应该不是这么用 我也在查这个
> 
> app('swoole.server') or app(Server::class)->task(xxxx);

ontask监控怎么设置的呢？我用think的listener没用

**Comment by twomiao** [comment]
> > > 应该不是这么用 我也在查这个
> > 
> > 
> > app('swoole.server') or app(Server::class)->task(xxxx);
> 
> ontask监控怎么设置的呢？我用think的listener没用

详细步骤：

1. app/event.php，添加自定义监听器：'listen' => [ 'swoole.task' => \app\listener\TaskListener::class] 
2. 控制器使用： app('swoole.server')->task($this->request->get());
3. 添加如下代码：
 `<?php
declare (strict_types=1);

namespace app\listener;

use Swoole\Server;
use Swoole\Server\Task;

class TaskListener
{
    /**
     * 事件监听处理
     * @param Task $task
     */
    public function handle(Task $task)
    {
        $data = $task->data;
        dump(getmypid());
        dump($task->id);
        dump($data);
    }
}`

**Comment by zengsuyi** [comment]
> > > > 应该不是这么用 我也在查这个
> > > 
> > > 
> > > app('swoole.server') or app(Server::class)->task(xxxx);
> > 
> > 
> > ontask监控怎么设置的呢？我用think的listener没用
> 
> 详细步骤：
> 
> 1. app/event.php，添加自定义监听器：'listen' => [ 'swoole.task' => \app\listener\TaskListener::class]
> 2. 控制器使用： app('swoole.server')->task($this->request->get());
> 3. 添加如下代码：
>    `<?php
>    declare (strict_types=1);
> 
> namespace app\listener;
> 
> use Swoole\Server;
> use Swoole\Server\Task;
> 
> class TaskListener
> {
> /**
> * 事件监听处理
> * @param Task $task
> */
> public function handle(Task $task)
> {
> $data = $task->data;
> dump(getmypid());
> dump($task->id);
> dump($data);
> }
> }`

谢谢  我试一下

**Comment by LonelySally** [comment]
> > > > 应该不是这么用 我也在查这个
> 
> > > 
> 
> > > 
> 
> > > app('swoole.server') or app(Server::class)->task(xxxx);
> 
> > 
> 
> > ontask监控怎么设置的呢？我用think的listener没用
> 
> 
> 
> 详细步骤：
> 
> 
> 
> 1. app/event.php，添加自定义监听器：'listen' => [ 'swoole.task' => \app\listener\TaskListener::class] 
> 
> 2. 控制器使用： app('swoole.server')->task($this->request->get());
> 
> 3. 添加如下代码：
> 
>  `<?php
> 
> declare (strict_types=1);
> 
> 
> 
> namespace app\listener;
> 
> 
> 
> use Swoole\Server;
> 
> use Swoole\Server\Task;
> 
> 
> 
> class TaskListener
> 
> {
> 
>     /**
> 
>      * 事件监听处理
> 
>      * @param Task $task
> 
>      */
> 
>     public function handle(Task $task)
> 
>     {
> 
>         $data = $task->data;
> 
>         dump(getmypid());
> 
>         dump($task->id);
> 
>         dump($data);
> 
>     }
> 
> }`

大佬，task的finish要怎么监听知道吗？在tp6里死活监听不到…然后监听了task，webscoket的emit就会被这个监听截获，扩展的监听不执行有什么办法解决一下吗……issue都没人回的
