### ISSUE TITLE
PidManager.php 中第64行代码，主进程或者管理者进程是否运行；判断似乎无意义。

### ISSUE THREAD

**Issue by twomiao** [top-think/think-swoole#130]
> 问题代码：

` getPids() 方法：返回值永远都是 == 2
`
` isRunning() 方法：
       if (!count($pids)) { 
            return false;
        } # 这里永远都不会执行
`

> 建议：

`
$pids = [1999,8888];
$masterPid = $pids[0] ?? null;
$managerPid = $pids[1] ?? null;

return $pids ? compact('masterPid', 'managerPid') : [];
`

**Comment by yunwuxin** [comment]
已调整
