### ISSUE TITLE
希望修复 一个连接被多个协程用的问题

### ISSUE THREAD

**Issue by rexleimo** [top-think/think-swoole#134]
[think\exception\ErrorException]
  Uncaught Swoole\Error: Socket#15 has already been bound to another coroutine#4, read
  ing of the same socket in coroutine#3 at the same time is not allowed in /mnt/hgfs/p
  hpDirs/zombienormandy_appstore/vendor/topthink/think-orm/src/db/PDOConnection.php:69
  5
  Stack trace:
  #0 /mnt/hgfs/phpDirs/zombienormandy_appstore/vendor/topthink/think-orm/src/db/PDOCon
  nection.php(695): PDO->prepare('SELECT * FROM `...')
  #1 /mnt/hgfs/phpDirs/zombienormandy_appstore/vendor/topthink/think-orm/src/db/PDOCon
  nection.php(639): think\db\PDOConnection->getPDOStatement('SELECT * FROM `...', Arra
  y, false, false)
  #2 /mnt/hgfs/phpDirs/zombienormandy_appstore/vendor/topthink/think-orm/src/db/PDOCon
  nection.php(799): think\db\PDOConnection->query(Object(think\db\Query), 'SELECT * FR
  OM `...')
  #3 /mnt/hgfs/phpDirs/zombienormandy_appstore/vendor/topthink/think-orm/src/db/BaseQu
  ery.php(1127): think\db\PDOConnection->find(Object(think\db\Query))
  #4 /mnt/hgfs/phpDirs/zombienormandy_appstore/app/repo/Base.php(20): think\db\BaseQue
  ry->find()
  #5 /mnt/hg

**Comment by yunwuxin** [comment]
哪个版本的

**Comment by rexleimo** [comment]
3.0


| |
莫东
|
|
rainbowmorel@163.com
|
签名由网易邮箱大师定制
在2020年5月25日 10:54，云无心<notifications@github.com> 写道：

哪个版本的

**Comment by rexleimo** [comment]
| |
莫东
|
|
rainbowmorel@163.com
|
jemter  高并发下就出现这个问题了 60个线程
签名由网易邮箱大师定制
在2020年5月25日 10:54，云无心<notifications@github.com> 写道：

哪个版本的

**Comment by xiangjihan** [comment]
上连接池。我自己定义了一个redis连接池，可以用

**Comment by yunwuxin** [comment]
如果是3.0版本  检查下是否开启了数据库连接池功能

**Comment by HyperLife1119** [comment]
> 上连接池。我自己定义了一个redis连接池，可以用

可是think-swoole不是自带连接池吗，自带的连接池似乎有问题？
