### ISSUE TITLE
在框架中如何使用Channel?

### ISSUE THREAD

**Issue by LonelySally** [top-think/think-swoole#136]
如何定义一个全局的变量(Channel)?
如何定义一个各worker之间共享的Class?
假设在ManagerStart中实现了多个Process消费者,在不使用外部队列的情况下(使用php的SplQueue),该如何共享这个实例并在各个worker的controller逻辑语句中投递数据?(PS:类似于Swoole\Table的概念)

**Comment by yunwuxin** [comment]
不存在全局变量  每个worker的内存数据都是独立的  worker之间的数据共享参考swoole文档

**Comment by yunwuxin** [comment]
不存在全局变量  每个worker的内存数据都是独立的  worker之间的数据共享参考swoole文档

**Comment by LonelySally** [comment]
> 不存在全局变量 每个worker的内存数据都是独立的 worker之间的数据共享参考swoole文档

那框架内Channel是无法使用的吗?

**Comment by yunwuxin** [comment]
可以用啊  Channel是用于协程间的通讯   又不能用于进程间的数据共享

**Comment by LonelySally** [comment]
emm...就是假设在workerStart的时候创建一个chan并执行了消费,然后在控制器中怎么把这个消息投过去?例如Go 只需要把这个chan共享出来就可以(头字母大写).就是像实现制这样一个功能.

**Comment by yunwuxin** [comment]
你这种需求应该是使用swoole的task
https://wiki.swoole.com/#/start/start_task
