### ISSUE TITLE
如何使用自定义的定时器

### ISSUE THREAD

**Issue by numa001** [top-think/think-swoole#145]

**Comment by yunwuxin** [comment]
事件里创建定时器 比如 swoole.start

**Comment by numa001** [comment]
> 事件里创建定时器 比如 swoole.start
在 class WebSocketEvent  加了个事件，
  public function onStart($worker_id)
    {
        if($worker_id == 0){
            swoole_timer_tick(1000*60, function () {
                //echo "tick  1500ms.\n";
            });
        }
}
。。。没用。。到底怎么用？ 我想这个定时器随服务启动（不要重复创建）
