### ISSUE TITLE
在swoole上运行tp6.0使用 php think optimize:route 会导致请求接口报错

### ISSUE THREAD

**Issue by leihenshang** [top-think/think-swoole#148]
在swoole上运行tp6.0使用 php think optimize:route 会导致请求接口报错
命令
php think optimize:route
然后启动
php think swoole
报错
` [think\exception\ErrorException]
  Uncaught Error: Call to a member function make() on null in /mnt/d/webProject/shopping_system_php_api_swoole/vendor/topthink/think-swoo
  le/src/concerns/InteractsWithPools.php:25
  Stack trace:
  #0 /mnt/d/webProject/shopping_system_php_api_swoole/vendor/topthink/think-swoole/src/concerns/InteractsWithPools.php(50): think\swoole\
  Manager->getPools()
  #1 /mnt/d/webProject/shopping_system_php_api_swoole/vendor/topthink/framework/src/think/Container.php(292): think\swoole\Manager->think
  \swoole\concerns\{closure}()
  #2 /mnt/d/webProject/shopping_system_php_api_swoole/vendor/topthink/framework/src/think/Container.php(356): think\Container->invokeFunc
  tion()
  #3 /mnt/d/webProject/shopping_system_php_api_swoole/vendor/topthink/framework/src/think/Event.php(260): think\Container->invoke()
  #4 /mnt/d/webProject/shopping_system_php_api_swoole/vendor/topthink/framework/src/think/Event.php(221): think\Event->dispatch()
  #5 /mnt/d/webProject/shopping_system_php_api_swoole/vendor/topthink/think-swoole/src/concerns/WithApplication.php(4
`

解决方法
php think clear 
清理一下就可以正常运行了。。。

路由文件的内容
`
Route::rule('ecommerce/php/:controller/:action', ':controller/:action');
Route::rule('ecommerce/php/:controller', ':controller/index');
`

**Comment by yunwuxin** [comment]
每次都会这样么

**Comment by yunwuxin** [comment]
已重现   正在修复

**Comment by yunwuxin** [comment]
> [think\exception\ErrorException] Uncaught Error: Call to a member function make() on null
这个问题已经修正了 

但是`php think optimize:route`这个命令在swoole下还是不能使用的，这个命令生成的缓存里使用了一个swoole下不支持的包，swoole下也没必要使用这个命令的，在think-swoole中路由只会注册一次，然后复用的

**Comment by leihenshang** [comment]
> 
> 
> > [think\exception\ErrorException] Uncaught Error: Call to a member function make() on null
> > 这个问题已经修正了
> 
> 但是`php think optimize:route`这个命令在swoole下还是不能使用的，这个命令生成的缓存里使用了一个swoole下不支持的包，swoole下也没必要使用这个命令的，在think-swoole中路由只会注册一次，然后复用的

好的。不过可以加一个检测吗？如果安装有swoole的相关包就做一个提示，或者如果有swoole包就忽略生成路由缓存。

**Comment by yunwuxin** [comment]
> 好的。不过可以加一个检测吗？如果安装有swoole的相关包就做一个提示，或者如果有swoole包就忽略生成路由缓存。

框架已经更新支持了
