### ISSUE TITLE
安装报错

### ISSUE THREAD

**Issue by mkerj** [top-think/think-swoole#149]
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - topthink/think-swoole v3.0.8 requires ext-swoole >=4.4.8 -> the requested PHP extension swoole is missing from your system.
    - topthink/think-swoole v3.0.7 requires ext-swoole >=4.4.8 -> the requested PHP extension swoole is missing from your system.
    - topthink/think-swoole v3.0.6 requires ext-swoole >=4.4.8 -> the requested PHP extension swoole is missing from your system.
    - topthink/think-swoole v3.0.5 requires ext-swoole >=4.0.0 -> the requested PHP extension swoole is missing from your system.
    - topthink/think-swoole v3.0.4 requires ext-swoole >=4.0.0 -> the requested PHP extension swoole is missing from your system.
    - topthink/think-swoole v3.0.3 requires ext-swoole >=4.0.0 -> the requested PHP extension swoole is missing from your system.
    - topthink/think-swoole v3.0.2 requires ext-swoole >=4.0.0 -> the requested PHP extension swoole is missing from your system.
    - topthink/think-swoole v3.0.1 requires ext-swoole >=4.0.0 -> the requested PHP extension swoole is missing from your system.
    - topthink/think-swoole v3.0.0 requires ext-swoole >=4.0.0 -> the requested PHP extension swoole is missing from your system.
    - Installation request for topthink/think-swoole ^3.0 -> satisfiable by topthink/think-swoole[v3.0.0, v3.0.1, v3.0.2, v3.0.3, v3.0.4, v3.0.5, v3.0.6, v3.0.7, v3.0.8].

**Comment by yunwuxin** [comment]
错误信息不提示的很清楚了吗

**Comment by mkerj** [comment]
swoole 是安装好的。 嗯 谢谢~！已解决了，是因为有多个 php版本造成的，
