### ISSUE TITLE
installation of think-swoole error

### ISSUE THREAD

**Issue by yeoman-chen** [top-think/think-swoole#15]
php version: 7.0.13
swoole version: 1.10.5
installation tips: 

Fatal error: Uncaught TypeError: Return value of Endroid\Installer\Installer::activate() must be an instance of Endroid\Installer\void, none returned in /mnt/hgfs/www/saletool/vendor/endroid/installer/src/Installer.php:36
Stack trace:
#0 phar:///usr/local/bin/composer/src/Composer/Plugin/PluginManager.php(232): Endroid\Installer\Installer->activate(Object(Composer\Composer), Object(Composer\IO\ConsoleIO))
#1 phar:///usr/local/bin/composer/src/Composer/Plugin/PluginManager.php(205): Composer\Plugin\PluginManager->addPlugin(Object(Endroid\Installer\Installer))
#2 phar:///usr/local/bin/composer/src/Composer/Plugin/PluginManager.php(257): Composer\Plugin\PluginManager->registerPackage(Object(Composer\Package\CompletePackage))
#3 phar:///usr/local/bin/composer/src/Composer/Plugin/PluginManager.php(76): Composer\Plugin\PluginManager->loadRepository(Object(Composer\Repository\InstalledFilesystemRepository))
#4 phar:///usr/local/bin/composer/src/Composer/Factory.php(377): Composer\Plugin\PluginManager->loadInstalledPlugins()
#5 p in /mnt/hgfs/www/saletool/vendor/endroid/installer/src/Installer.php on line 36

**Comment by liu21st** [comment]
你这个和think-swoole扩展有啥关系
