### ISSUE TITLE
无法获取到post参数

### ISSUE THREAD

**Issue by zpzxgcr** [top-think/think-swoole#165]
排查了一下无法获取到post参数$_REQUEST, $request->param(), $_POST, $request->header() 都试过了 全部是空 然后在社区也找到类似情况
[http://www.thinkphp.cn/bug/4889.html](查看)

**Comment by supernarsi** [comment]
我也遇到，目前是用 $request->getInput() 获取原始 input 数据，自己解析的。

**Comment by yunwuxin** [comment]
合规的请求里的数据都会正常获取到的  

除非你的header和content内容不一致   
比如你body里放的是一个json字符串  但是header里的content-type写的却不是json类型
