### ISSUE TITLE
代码里使用redis报错(【这表示在两个协程内使用了同一个客户端】)

### ISSUE THREAD

**Issue by numa001** [top-think/think-swoole#167]
日志报错如下：
[1]Uncaught Swoole\Error: Socket#455 has already been bound to another coroutine#5442, reading of the same socket in coroutine#5443 at the same time is not allowed in /www/wwwroot/school_swoole/vendor/topthink/framework/src/think/cache/Driver.php:345

Bdiudu 后  得知 【这表示在两个协程内使用了同一个客户端】
应该是我没有用正确使用redis(连接池)的缘故
我的项目的代码(当然，我在配置文件里开启了redis)：
`   public function __construct(Server $server, Websocket $websocket, Container $container, Room $room)
    {
       ................
        $this->redis = new Redis(['select'=>1]);
    }

 public function onConnect(Request $request){
        .......
        $this->redis->hMset($user_id,[
                'fd' => $fd,
                'user_id' => $user_id,
                'type' => $user_info['type'],
                'nickname' => $user_info['name'],
                'avatar' => $user_info['avatar'],
                'room_id' => $room_id
            ]);
}`

我如何正确使用 ？

**Comment by HyperLife1119** [comment]
不要试图在构造方法里保存Redis连接实例。

**Comment by HyperLife1119** [comment]
你应该使用一个局部变量来暂存Redis，使用完之后它会自动释放。

**Comment by numa001** [comment]
> 你应该使用一个局部变量来暂存Redis，使用完之后它会自动释放。

谢谢， 问下 ， think-swoole 本身有没有带有解决方案 ？

**Comment by HyperLife1119** [comment]
> > 你应该使用一个局部变量来暂存Redis，使用完之后它会自动释放。
> 
> 谢谢， 问下 ， think-swoole 本身有没有带有解决方案 ？

这才是正确的使用方式，

> > 你应该使用一个局部变量来暂存Redis，使用完之后它会自动释放。
> 
> 谢谢， 问下 ， think-swoole 本身有没有带有解决方案 ？

参考一下我的示例: https://github.com/HyperLife1119/OnChat/blob/2a07d7dc8c9ff31dc14d70ffd872778a7768c220/app/listener/websocket/BaseListener.php#L51

使用Cache::store('redis')->getRedis()来获取Redis实例，而不是自己new一个Redis

**Comment by numa001** [comment]
@HyperLife1119
Cache::store('redis')->getRedis()   这是可以，能不能把think-swoole 的redis 连接池利用起来，我看think-swoole 本身是有 redis 连接池的相关代码的，但是我不知道怎么用。。

**Comment by HyperLife1119** [comment]
> @HyperLife1119
> Cache::store('redis')->getRedis() 这是可以，能不能把think-swoole 的redis 连接池利用起来，我看think-swoole 本身是有 redis 连接池的相关代码的，但是我不知道怎么用。。

think swoole内部已经代理了这个，已经用到了连接池

**Comment by numa001** [comment]
> > @HyperLife1119
> > Cache::store('redis')->getRedis() 这是可以，能不能把think-swoole 的redis 连接池利用起来，我看think-swoole 本身是有 redis 连接池的相关代码的，但是我不知道怎么用。。
> 
> think swoole内部已经代理了这个，已经用到了连接池

恕我愚笨，我的代码里怎么去使用这个 连接池？

**Comment by HyperLife1119** [comment]
> > > @HyperLife1119
> > > Cache::store('redis')->getRedis() 这是可以，能不能把think-swoole 的redis 连接池利用起来，我看think-swoole 本身是有 redis 连接池的相关代码的，但是我不知道怎么用。。
> > 
> > 
> > think swoole内部已经代理了这个，已经用到了连接池
> 
> 恕我愚笨，我的代码里怎么去使用这个 连接池？

就像我上面给你发的链接那样使用，think swoole内部已经代理实现了连接池

**Comment by numa001** [comment]
> > > > @HyperLife1119
> > > > Cache::store('redis')->getRedis() 这是可以，能不能把think-swoole 的redis 连接池利用起来，我看think-swoole 本身是有 redis 连接池的相关代码的，但是我不知道怎么用。。
> > > 
> > > 
> > > think swoole内部已经代理了这个，已经用到了连接池
> > 
> > 
> > 恕我愚笨，我的代码里怎么去使用这个 连接池？
> 
> 就像我上面给你发的链接那样使用，think swoole内部已经代理实现了连接池

参考你这样写了，
还是会出现这样的错误:【[1]Uncaught Swoole\Error: Socket#455 has already been bound to another coroutine#161, reading of the same socket in coroutine#162 at the same time is not allowed in /www/wwwroot/school_swoole/app/listener/WebSocketEvent.php:192】
行192的代码： $user_info = $this->getRedis()->hGetAll((string)$user_id);
。。。不知道为什么。。

**Comment by anydson** [comment]
> > > > > @HyperLife1119
> > > > > Cache::store('redis')->getRedis() 这是可以，能不能把think-swoole 的redis 连接池利用起来，我看think-swoole 本身是有 redis 连接池的相关代码的，但是我不知道怎么用。。
> > > > 
> > > > 
> > > > think swoole内部已经代理了这个，已经用到了连接池
> > > 
> > > 
> > > 恕我愚笨，我的代码里怎么去使用这个 连接池？
> > 
> > 
> > 就像我上面给你发的链接那样使用，think swoole内部已经代理实现了连接池
> 
> 参考你这样写了，
> 还是会出现这样的错误:【[1]Uncaught Swoole\Error: Socket#455 has already been bound to another coroutine#161, reading of the same socket in coroutine#162 at the same time is not allowed in /www/wwwroot/school_swoole/app/listener/WebSocketEvent.php:192】
> 行192的代码： $user_info = $this->getRedis()->hGetAll((string)$user_id);
> 。。。不知道为什么。。

-------------------------------------------------------------
public function __construct(Server $server, Websocket $websocket, Container $container) {
    $this->redis = $container->get(Cache::class);
}

**Comment by numa001** [comment]
@anydson 
use think\facade\Cache;
__construct  里面：
$this->redis = $container->get(Cache::class);
。。提示报错 ： 
【Uncaught think\exception\ClassNotFoundException: class not exists: think\facade\Cache in /www/wwwroot/school_swoole/vendor/topthink/framework/src/think/Container.php:133】

**Comment by anydson** [comment]
> use think\facade\Cache;

use think\swoole\pool\Cache

**Comment by numa001** [comment]
> > use think\facade\Cache;
> 
> use think\swoole\pool\Cache
public function __construct(Server $server, Websocket $websocket, Container $container) {
$this->redis = $container->get(Cache::class);
}
然后在方法里 怎么使用呢？打印$this->redis是一个空值。。

**Comment by anydson** [comment]
> > > use think\facade\Cache;
> > 
> > 
> > use think\swoole\pool\Cache
> > public function __construct(Server $server, Websocket $websocket, Container $container) {
> > $this->redis = $container->get(Cache::class);
> > }
> > 然后在方法里 怎么使用呢？打印$this->redis是一个空值。。

$this->redis->set('user', 1);
$id = $this->redis->get('user');
dump($id);

**Comment by anydson** [comment]
官方已配置了Redis连接池信息
```
'websocket'  => [
        'enable'        => true,
        'handler'       => Handler::class,
        'parser'        => Parser::class,
        'ping_interval' => 25000,
        'ping_timeout'  => 60000,
        'room'          => [
            'type'  => 'table',
            'table' => [
                'room_rows'   => 4096,
                'room_size'   => 2048,
                'client_rows' => 8192,
                'client_size' => 2048,
            ],
            'redis' => [ # Redis连接池配置信息
                'host'          => '127.0.0.1',
                'port'          => 6379,
                'max_active'    => 3,
                'max_wait_time' => 5,
            ],
        ],
        'listen'        => [],
        'subscribe'     => [
            WebSocketEvent::class
        ],
    ],
```

**Comment by numa001** [comment]
> get
hMset 等不能用？
$this->redis->hMset('test',['id'=>1,'avatar'=>'']); 报错：
call_user_func_array() expects parameter 1 to be a valid callback, first array member is not a valid class name or object

**Comment by numa001** [comment]
> > > > use think\facade\Cache;
> > > 
> > > 
> > > use think\swoole\pool\Cache
> > > public function __construct(Server $server, Websocket $websocket, Container $container) {
> > > $this->redis = $container->get(Cache::class);
> > > }
> > > 然后在方法里 怎么使用呢？打印$this->redis是一个空值。。
> 
> $this->redis->set('user', 1);
> $id = $this->redis->get('user');
> dump($id);

hMset  等不能用 ？
$this->redis->hMset('test',['id'=>1,'avatar'=>'xxx'])  报错
call_user_func_array() expects parameter 1 to be a valid callback, first array member is not a valid class name or object

**Comment by anydson** [comment]
> > > > > use think\facade\Cache;
> > > > 
> > > > 
> > > > use think\swoole\pool\Cache
> > > > public function __construct(Server $server, Websocket $websocket, Container $container) {
> > > > $this->redis = $container->get(Cache::class);
> > > > }
> > > > 然后在方法里 怎么使用呢？打印$this->redis是一个空值。。
> > 
> > 
> > $this->redis->set('user', 1);
> > $id = $this->redis->get('user');
> > dump($id);
> 
> hMset 等不能用 ？
> $this->redis->hMset('test',['id'=>1,'avatar'=>'xxx']) 报错
> call_user_func_array() expects parameter 1 to be a valid callback, first array member is not a valid class name or object

数据未序列化,需要自己序列化

**Comment by anydson** [comment]
> > > > > use think\facade\Cache;
> > > > 
> > > > 
> > > > use think\swoole\pool\Cache
> > > > public function __construct(Server $server, Websocket $websocket, Container $container) {
> > > > $this->redis = $container->get(Cache::class);
> > > > }
> > > > 然后在方法里 怎么使用呢？打印$this->redis是一个空值。。
> > 
> > 
> > $this->redis->set('user', 1);
> > $id = $this->redis->get('user');
> > dump($id);
> 
> hMset 等不能用 ？
> $this->redis->hMset('test',['id'=>1,'avatar'=>'xxx']) 报错
> call_user_func_array() expects parameter 1 to be a valid callback, first array member is not a valid class name or object

think\swoole\pool\Cache 扩展于 think\Cache, 具体使用请看thinkphp6官方文档
