### ISSUE TITLE
使用think-swoole开启了mysql日志监听无法监听到sql

### ISSUE THREAD

**Issue by doesDWQ** [top-think/think-swoole#169]
翻源码发现是使用了swoole连接池后导致的，sql日志没有落盘，全局长时间保存内存，是不是可能会导致内存泄漏(目前没碰到泄漏)

**Comment by yunwuxin** [comment]
你是使用的最新版么   我记得最新版修正过的

**Comment by doesDWQ** [comment]
"topthink/km-swoole":"dev-master",   composer中显示的这个算是最新版本吗

**Comment by yunwuxin** [comment]
确定是这个？

**Comment by doesDWQ** [comment]
这个被leader托管到服务器上了。。。我怎么知道这个插件的版本？

**Comment by yunwuxin** [comment]
看你composer.json里写的  tp是什么版本的

**Comment by doesDWQ** [comment]
"topthink/framework": "^6.0.0",

**Comment by yunwuxin** [comment]
think-swoole的呢

**Comment by doesDWQ** [comment]
这个我也不知道了哎

**Comment by doesDWQ** [comment]
{
    "name": "topthink/think",
    "description": "the new thinkphp framework",
    "type": "project",
    "keywords": [
        "framework",
        "thinkphp",
        "ORM"
    ],
    "homepage": "http://thinkphp.cn/",
    "license": "Apache-2.0",
    "authors": [
        {
            "name": "liu21st",
            "email": "liu21st@gmail.com"
        },
        {
            "name": "yunwuxin",
            "email": "448901948@qq.com"
        }        
    ],
    "require": {
        "php": ">=7.1.0",
        "topthink/framework": "^6.0.0",
        "topthink/think-orm": "^2.0"
    },
    "require-dev": {
        "symfony/var-dumper": "^4.2",
        "topthink/think-trace":"^1.0",
        "topthink/think-multi-app": "^1.0",
        "elasticsearch/elasticsearch": "^7.3",
        "jpush/jpush": "^3.6",
        "aliyuncs/oss-sdk-php": "^2.3",
        "phpoffice/phpspreadsheet": "^1.10",
        "overtrue/pinyin": "^4.0",
        "pcrov/jsonreader": "^1.0",
        "topthink/km-queue":"dev-master",
        "topthink/km-swoole":"dev-master",
        "topthink/think-migration": "^3.0"
    },
    "autoload": {
        "psr-4": {
            "app\\": "app"
        },
        "psr-0": {
            "": "extend/"
        }
    },
    "config": {
        "preferred-install": "dist",
        "sort-packages": true,
        "optimize-autoloader": true,
        "secure-http": false
    },
    "scripts": {
        "post-autoload-dump": [
            "@php think service:discover",
            "@php think vendor:publish"
        ]
    },
    "repositories": [
         {
            "type": "git",
            "url":"私人仓库/km-queue.git"
         },
         {
            "type": "git",
            "url":"私人仓库/km-swoole.git"
         }
    ]
}

这个是上面的composer.json文件

**Comment by doesDWQ** [comment]
删掉了原来的版本，安装了最新的版本 Installing topthink/think-swoole (v3.0.9): Downloading (100%) 发现这个问题还是存在的
