### ISSUE TITLE
如何在web（不是websocket）的控制器里 查看 swoole_table  里的内容

### ISSUE THREAD

**Issue by numa001** [top-think/think-swoole#170]
我的websocket项目里建了个 swoole_table  （table_user）
在websocket 项目里 能够正常读写
但是如何 通过访问 web的方式去 读写 table_user 
app/controller/index.php  中
`    public function c(\think\swoole\Table $table)
    {
        halt($table); //空
    }` 
![image](https://user-images.githubusercontent.com/7803318/95945261-a67cc500-0e1c-11eb-93c3-d52bbe39e341.png)
我的项目目录：
![image](https://user-images.githubusercontent.com/7803318/95945360-ddeb7180-0e1c-11eb-92ec-711b21d176ff.png)
（ps   所有监听事件都放在了 WebSocketEvent.php 文件中）

**Comment by yunwuxin** [comment]
我刚测试是可以正常读取的

**Comment by numa001** [comment]
> 我刚测试是可以正常读取的

通过web的方式访问   形如  http://xxx.com/index.php/index/c  打印出来  halt($table)  不为空？？

**Comment by yunwuxin** [comment]
你这个地址肯定是不对的     也需要通过由swoole提供的http服务访问   不经过index.php的
