### ISSUE TITLE
emti （调用了task）方法执行后，如何监听对应的finish事件

### ISSUE THREAD

**Issue by numa001** [top-think/think-swoole#171]
源代码中。
`          
public function emit(string $event, $data = null): bool{
$result = $this->server->task([
               .....
            ]);
}  `

emit方法执行后（emti 方法中调用了task）,  我想 监听对应的finish事件， 怎么写？
（项目中 给房间里的多个成员发消息，有时候某个成员会 延迟收到消息，我想在finish事件中纪录下时间， 好对比下   ）

**Comment by LonelySally** [comment]
在task监听中必须手动触发finish.$task->finish($task->data);
[参考链接](https://www.kancloud.cn/book_xwy/think-swoole3/1724504)
