### ISSUE TITLE
没有找到开启 http2 协议的配置

### ISSUE THREAD

**Issue by balloontmz** [top-think/think-swoole#176]
如题，在 `swoole.server.options` 中添加 `open_http2_protocol=>true,`参数无效，想问下是否支持该参数，或者应该怎么配置。

**Comment by balloontmz** [comment]
目的是通过 http2 服务的方式支持 grpc 服务端。因为现有产品大多数是采用 tp5.1 写的，想最大程度复用代码。

**Comment by yunwuxin** [comment]
这个要你自己编译swoole 开启http2
