### ISSUE TITLE
线程数报错

### ISSUE THREAD

**Issue by zhigge** [top-think/think-swoole#182]
`[Smf\ConnectionPool\BorrowConnectionTimeoutException]                                 
  Borrow the connection timeout in 5.00(s), connections in pool: 0, all connections: 3`

就我一个人测试也经常报错

版本3.0.9

**Comment by yunwuxin** [comment]
连接池使用不当  导致不能回收  
连接池里的连接 你是不能保存下来的

**Comment by OverNaive** [comment]
请教一下，用 facade 算不算保存了连接？

我建了一个 redis 类，构造函数如下：

```
    /**
     * RedisService constructor.
     * @param App $app
     */
    public function __construct(App $app)
    {
        $this->redis = $app->cache->store('redis')->handler();
    }
```

创建了一个对应的 facade。

这样算不算保存了连接？因为我目前遇到这个报错，但是排查的时候一直复现不出来，有点困惑。

**Comment by yunwuxin** [comment]
算 你这个把handler保存下来了

```
    /**
     * RedisService constructor.
     * @param App $app
     */
    public function __construct(App $app)
    {
        $this->redis = $app->cache->store('redis');
    }
```

只能这样保存

**Comment by OverNaive** [comment]
> 算 你这个把handler保存下来了
> 
> ```
>     /**
>      * RedisService constructor.
>      * @param App $app
>      */
>     public function __construct(App $app)
>     {
>         $this->redis = $app->cache->store('redis');
>     }
> ```
> 
> 只能这样保存

非常感谢！
