### ISSUE TITLE
如何随着 think-swoole 服务启动而开启一个定时器？

### ISSUE THREAD

**Issue by numa001** [top-think/think-swoole#183]

**Comment by numa001** [comment]
这样？ 没有生效；
`public function onWorkerStart($worker_id)
    {   
        if($worker_id == 0){
            swoole_timer_tick(1000*60, function () {
                echo "tick  触发.\n";
            });
        }
    }`

**Comment by numa001** [comment]
@yunwuxin  百度了一圈，尝试了其它写法，都不成，求助大佬。

**Comment by qq475281441** [comment]
大佬不是回答过你了

https://github.com/top-think/think-swoole/issues/145#issuecomment-659180108

**Comment by numa001** [comment]
> 大佬不是回答过你了
> 
> [#145 (comment)](https://github.com/top-think/think-swoole/issues/145#issuecomment-659180108)
你看清楚没？ 那个是我自己的回复，那样写也没用。。

**Comment by yunwuxin** [comment]
首先确认一下  你事件有没有注册成功   创建定时器的代码执行到了没

**Comment by numa001** [comment]
> 首先确认一下 你事件有没有注册成功 创建定时器的代码执行到了没
都注册了呀
![image](https://user-images.githubusercontent.com/7803318/100058894-168f5980-2e65-11eb-94aa-045ed2b31681.png)
![image](https://user-images.githubusercontent.com/7803318/100063240-dd0e1c80-2e6b-11eb-8821-0282da1d91ca.png)

就是没有生效

**Comment by qq475281441** [comment]
在swoole.php配置文件里面配置的事件会自动加上前缀  swoole.websocket  所以你监听的是 swoole.websocket.swoole.start
但是他启动的时候触发的是swoole.start

![image](https://user-images.githubusercontent.com/14217045/100065286-9110a700-2e6e-11eb-822c-a6686ea9f682.png)

**Comment by qq475281441** [comment]
一样的代码，我的可以触发

class onStart
{
	public function handle($data)
	{
		swoole_timer_tick(1000 * 2, function () {
			echo "tick 触发.\n";
		});
		return;
	}
}

![image](https://user-images.githubusercontent.com/14217045/100065793-2f9d0800-2e6f-11eb-91e5-5ec32bb2c9ec.png)

**Comment by numa001** [comment]
> 一样的代码，我的可以触发
> 
> class onStart
> {
> public function handle($data)
> {
> swoole_timer_tick(1000 * 2, function () {
> echo "tick 触发.\n";
> });
> return;
> }
> }
> 
> ![image](https://user-images.githubusercontent.com/14217045/100065793-2f9d0800-2e6f-11eb-91e5-5ec32bb2c9ec.png)

我在 event.php 中注册可以的， 在swoole.php中注册死活不行。。。不知道为什么。。。

**Comment by yunwuxin** [comment]
swoole.php里注册的是websocket的事件
