### ISSUE TITLE
think-swoole在TP6开启多应用模式首次访问异常会导致路由失效

### ISSUE THREAD

**Issue by etjson** [top-think/think-swoole#184]
think-swoole在TP6开启多应用模式下如果某个路由没有访问过一次，那么其他报错，哪怕是404控制器不存在也会导致没有访问过的路由直接失效。

目前很挫的方法就是在重启后或者启动后第一时间访问每一个路由，使其路由生效，然后其他报错就不会导致路由失效。

**Comment by yunwuxin** [comment]
https://github.com/top-think/think-swoole/issues/121#issuecomment-597222363
