### ISSUE TITLE
swoole 4 .5 报错

### ISSUE THREAD

**Issue by zhouyouth** [top-think/think-swoole#186]
[think\exception\ErrorException]
--
  | Uncaught think\exception\ErrorException: unsupported option [host] in @swoole-src/library/core/Server/Helper.php:160
  | Stack trace:
  | #0 [internal function]: think\Error::appError(512, 'unsupported opt...', '@swoole-src/lib...', 160, Array)
  | #1 @swoole-src/library/core/Server/Helper.php(160): trigger_error('unsupported opt...', 512)
  | #2 [internal function]: Swoole\Server\Helper::checkOptions(Array)
  | #3 [internal function]: Swoole\Server\Port->set(Array)
  | #4 /data/tars/tarsnode-data/PHP.topthinkServer/bin/src/vendor/topthink/think-swoole/src/Http.php(110): Swoole\Server->set(Array)
  | #5 /data/tars/tarsnode-data/PHP.topthinkServer/bin/src/vendor/topthink/think-swoole/src/command/Swoole.php(146): think\swoole\Http->option(Array)
  | #6 /data/tars/tarsnode-data/PHP.topthinkServer/bin/src/vendor/topthink/think-swoole/src/command/Swoole.php(50): think\swoole\command\Swoole->start()
  | #7 /data/tars/tarsnode-data/PHP.topthinkServer/bin/src/thinkphp/library/think/console/Command.php(175): think\swoole\comman

**Comment by sy-records** [comment]
```bash
composer require topthink/think-swoole:2.0.x-dev
```

https://wenda.swoole.com/detail/107645
