### ISSUE TITLE
Websocket 中加上 disconnect

### ISSUE THREAD

**Issue by OverNaive** [top-think/think-swoole#187]
既然给 Websocket 类加了 isEstablished 方法，那么是否考虑加上 disconnect 方法呢？

👍

**Comment by yunwuxin** [comment]
本来不就有close方法

**Comment by OverNaive** [comment]
disconnect 可以带上 code reason 来告诉客户端断开的原因。比如连接鉴权过程中失败了，可以直接 disconnect ，然后带上 code reason（有点像API中的状态码）
