### ISSUE TITLE
mac 系统无法修改swoole 进程名称bug

### ISSUE THREAD

**Issue by zhouyouth** [top-think/think-swoole#194]
swoole_set_process_name(): cli_set_process_title had an error: Not initialized correctly

**Comment by yunwuxin** [comment]
https://github.com/top-think/think-swoole/blob/7ffb18e1e4e4701820879a92967810a9a51b8a3b/src/concerns/InteractsWithServer.php#L195-L200

是3.0版本吗  这里不是判断过了  mac下是不修改进程名称的

**Comment by zhouyouth** [comment]
直接 composer require topthink/think-swoole  安装的是3.0.2 是没有你上面的那个文件的, 运行php think swoole 还是会报修改进程名称错误

**Comment by yunwuxin** [comment]
最新的都已经3.0.10了  你用的composer镜像有问题吧

**Comment by zhouyouth** [comment]
我的composer 镜像源是阿里的 [repositories.packagist.org.url] https://mirrors.aliyun.com/composer/
可能是源的问题
