### ISSUE TITLE
config/swoole.php不支持.env？

### ISSUE THREAD

**Issue by aweihaitun** [top-think/think-swoole#200]
config/swoole.php不支持env里面的配置么？之前两个项目，env配置不同的swoole端口，启动后端口冲突，貌似没有用到env里面的配置，是不是swoole启动后才加载env配置？

**Comment by OverNaive** [comment]
版本：3.0 

看下这个热更新的配置

```
...
    'hot_update' => [
        'enable'  => env('APP_DEBUG', false),
        'name'    => ['*.php'],
        'include' => [app_path()],
        'exclude' => [],
    ],
...
```

里面就是从 env 文件里获取到 APP_DEBUG 的配置，默认值是 false。

不晓得你哪个版本的。

**Comment by aweihaitun** [comment]
不好意思，是我这边的问题，我检查了下代码，发现env中定义的变量直接复制到了swoole.php中，是大小写的问题
