### ISSUE TITLE
系统mac，php7.4 + swoole4.6.1。php think swoole后报下面的错

### ISSUE THREAD

**Issue by bestlake** [top-think/think-swoole#206]
全新环境，只引了几个包
    "require": {
        "php": ">=7.1.0",
        "topthink/framework": "^6.0.0",
        "topthink/think-orm": "^2.0",
        "topthink/think-multi-app": "^1.0",
        "topthink/think-swoole": "^3.1"
    },

系统mac，php7.4 + swoole4.6.1。php think swoole后报下面的错。

Swoole http server started: <http://127.0.0.1:8081>
You can exit with `CTRL-C`
flock(10, LOCK_EX) failed. Error: Interrupted system call[4]
write(log_fd=10, size=122) failed. Error: Interrupted system call[4].
Message: [2021-01-28 12:43:54 $37207.0]	WARNING	check_worker_exit_status: worker#12[pid=37248] abnormal exit, status=255, signal=0

flock(10, LOCK_EX) failed. Error: Interrupted system call[4]
write(log_fd=10, size=122) failed. Error: Interrupted system call[4].
Message: [2021-01-28 12:44:00 $37207.0]	WARNING	check_worker_exit_status: worker#13[pid=38758] abnormal exit, status=255, signal=0

flock(10, LOCK_EX) failed. Error: Interrupted system call[4]
write(log_fd=10, size=121) failed. Error: Interrupted system call[4].
Message: [2021-01-28 12:44:02 $37207.0]	WARNING	check_worker_exit_status: worker#3[pid=39035] abnormal exit, status=255, signal=0

flock(10, LOCK_EX) failed. Error: Interrupted system call[4]
write(log_fd=10, size=121) failed. Error: Interrupted system call[4].
Message: [2021-01-28 12:44:09 $37207.0]	WARNING	check_worker_exit_status: worker#1[pid=40110] abnormal exit, status=255, signal=0

flock(10, LOCK_EX) failed. Error: Interrupted system call[4]
write(log_fd=10, size=121) failed. Error: Interrupted system call[4].
Message: [2021-01-28 12:44:11 $37207.0]	WARNING	check_worker_exit_status: worker#6[pid=40341] abnormal exit, status=255, signal=0

**Comment by bestlake** [comment]
[2021-01-28T13:40:17+08:00][error] [1]Uncaught Error: Call to undefined function Smf\ConnectionPool\go() in /Volumes/DevDisk/workspace/tp6/vendor/open-smf/connection-pool/src/ConnectionPool.php:92
Stack trace:
#0 /Volumes/DevDisk/workspace/tp6/vendor/topthink/think-swoole/src/pool/Proxy.php(69): Smf\ConnectionPool\ConnectionPool->init()
#1 /Volumes/DevDisk/workspace/tp6/vendor/topthink/think-swoole/src/pool/Cache.php(13): think\swoole\pool\Proxy->__construct(Object(Closure), Array)
#2 /Volumes/DevDisk/workspace/tp6/vendor/topthink/framework/src/think/Manager.php(66): think\swoole\pool\Cache->createDriver('file')
#3 /Volumes/DevDisk/workspace/tp6/vendor/topthink/framework/src/think/Manager.php(56): think\Manager->getDriver('file')
#4 /Volumes/DevDisk/workspace/tp6/vendor/topthink/framework/src/think/Cache.php(90): think\Manager->driver('file')
#5 /Volumes/DevDisk/workspace/tp6/vendor/topthink/framework/src/think/Db.php(38): think\Cache->store(NULL)
#6 [internal function]: think\Db::__make(Object(think\Event), Object(think\Config), Object(think\Log

**Comment by sy-records** [comment]
`Call to undefined function Smf\ConnectionPool\go` 这个应该是你把短名关掉了，找的命名空间下的

`php --ri swoole`看看

**Comment by bestlake** [comment]
确实是shortname设置成Off了
