### ISSUE TITLE
能不能集成phpunit进来？

### ISSUE THREAD

**Issue by doesDWQ** [top-think/think-swoole#209]
能不能集成phpunit进来，或者说有没有什么现成直接能用的库，因为看见别的集成swoole的框架都有，打扰了

**Comment by yunwuxin** [comment]
哪方面的集成，现在不用能吗

**Comment by doesDWQ** [comment]
https://hyperf.wiki/2.1/#/zh-cn/testing?id=%e8%87%aa%e5%8a%a8%e5%8c%96%e6%b5%8b%e8%af%95    类似于hyperf这样的集成phpunit进来

**Comment by yunwuxin** [comment]
我们这个不需要的 tp框架本身有think-testing这个库 直接用这个就可以了

**Comment by doesDWQ** [comment]
好的，打扰你了

**Comment by doesDWQ** [comment]
但是tp6好像安装不上这个库，看了一下有人提了issue
