### ISSUE TITLE
安装失败了

### ISSUE THREAD

**Issue by Funny-dot** [top-think/think-swoole#214]
The "topthink/think-installer" plugin was skipped because it requires a Plugin A
PI version ("^1.0") that does not match your Composer installation ("2.0.0"). Yo
u may need to run composer update with the "--no-plugins" option.
Using version ^3.1 for topthink/think-swoole
./composer.json has been updated
The "topthink/think-installer" plugin was skipped because it requires a Plugin A
PI version ("^1.0") that does not match your Composer installation ("2.0.0"). Yo
u may need to run composer update with the "--no-plugins" option.
Running composer update topthink/think-swoole
Loading composer repositories with package information
Updating dependencies
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - topthink/think-installer v2.0.0 requires composer-plugin-api ^1.0 -> found
 composer-plugin-api[2.0.0] but it does not match the constraint.
    - topthink/think-queue v2.0.4 requires topthink/think-installer ^2.0 -> sati
sfiable by topthink/think-installer[v2.0.0].
    - topthink/think-queue is locked to version v2.0.4 and an update of this pac
kage was not requested.

You are using Composer 2, which some of your plugins seem to be incompatible wit
h. Make sure you update your plugins or report a plugin-issue to ask them to sup
port Composer 2.

Installation failed, reverting ./composer.json and ./composer.lock to their orig

**Comment by yunwuxin** [comment]
2.0版本下请使用composer v1
