### ISSUE TITLE
3.1.1版本Bug，建议修复

### ISSUE THREAD

**Issue by xiaojiakm** [top-think/think-swoole#216]
文件：src/pool/proxy/Connection.php 第166至177行

`/**
     * 得到某个列的数组
     * @access public
     * @param BaseQuery $query 查询对象
     * @param string $column 字段名 多个字段用逗号分隔
     * @param string $key 索引
     * @return array
     */
    public function column(BaseQuery $query, string $column, string $key = ''): array
    {
        return $this->__call(__FUNCTION__, func_get_args());
    }`
应改为：
`/**
     * 得到某个列的数组
     * @access public
     * @param BaseQuery $query 查询对象
     * @param string|array $column 字段名 多个字段用逗号分隔
     * @param string $key 索引
     * @return array
     */
    public function column(BaseQuery $query, $column, string $key = ''): array
    {
        return $this->__call(__FUNCTION__, func_get_args());
    }`

**Comment by sy-records** [comment]
https://github.com/top-think/think-swoole/commit/eb7f78b7eb53dde79257f4254fe61f9514f3c7d8

**Comment by taozhipeng1990** [comment]
composer 会默认安装3.1.
在3.1版本中是存在这个类型问题的。
composer使用的是阿里镜像。

**Comment by yunwuxin** [comment]
已release
