### ISSUE TITLE
method not exists:think\Request->withInput

### ISSUE THREAD

**Issue by wanganlin** [top-think/think-swoole#22]
`
[think\exception\ErrorException]                                                                                                
  Uncaught think\Exception: method not exists:think\Request->withInput in /home/vagrant/code/knowledge/thinkphp/library/  
  think/Request.php:335                                                                                                           
  Stack trace:                                                                                                                    
  #0 /home/vagrant/code/knowledge/vendor/topthink/think-swoole/src/Application.php(53): think\Request->__call('withInput  
  ', Array)                                                                                                                       
  #1 /home/vagrant/code/knowledge/vendor/topthink/think-swoole/src/Swoole.php(131): think\swoole\Application->swoole(Obj  
  ect(Swoole\Http\Request), Object(Swoole\Http\Response))                                                                         
  #2 {main}                                                                                                                       
    thrown         
`

**Comment by liu21st** [comment]
需要更新最新的框架核心
