### ISSUE TITLE
bug: 使用download()助手函数无法正常预览图片，下载文件

### ISSUE THREAD

**Issue by HyperLife1119** [top-think/think-swoole#223]
#### 当前行为
浏览器访问后，一直处于loading状态，无法正常预览图片，下载文件；
使用 `php think run` 开启的HTTP服务器则正常预览图片，下载文件

#### 相关代码
```php
public function download()
{
    return download('image.jpg', 'my.jpg')->force(false);
}
```

**Comment by sy-records** [comment]
这里应该是高版本swoole允许用户端设置Content-Length导致的，我看下怎么修复。

你可以先关闭压缩 https://wiki.swoole.com/#/http_server?id=http_compression

**Comment by HyperLife1119** [comment]
了解，感谢。希望尽快修复😊

**Comment by OverNaive** [comment]
我不认为这是个 bug

`php think` 命令都是在根目录下执行的。

所以默认的路径就是在根目录，如果要访问public内容，得加上 public

例子中里加上 public 即可访问到图片。

```
public function download()
{
    return download('public/image.jpg', 'my.jpg')->force(false);
}
```

为什么在 php think run 里能直接访问，不需要 public 路径呢，看代码：

```
    public function execute(Input $input, Output $output)
    {
        $host = $input->getOption('host');
        $port = $input->getOption('port');
        $root = $input->getOption('root');
        if (empty($root)) {
            $root = $this->app->getRootPath() . 'public';
        }

        $command = sprintf(
            'php -S %s:%d -t %s %s',
            $host,
            $port,
            escapeshellarg($root),
            escapeshellarg($root . DIRECTORY_SEPARATOR . 'router.php')
        );

        $output->writeln(sprintf('ThinkPHP Development server is started On <http://%s:%s/>', '0.0.0.0' == $host ? '127.0.0.1' : $host, $port));
        $output->writeln(sprintf('You can exit with <info>`CTRL-C`</info>'));
        $output->writeln(sprintf('Document root is: %s', $root));
        passthru($command);
    }
```

在执行 `php -S` 命令时，加了参数，而这里 $root 指定了 public。

所以为了适配 think-swoole，只需在路径上加上 public 即可。

**Comment by HyperLife1119** [comment]
事实上，我使用：
```php
public function download()
{
    return download(public_path() . 'image.jpg', 'my.jpg')->force(false);
}
```
路径是绝对路径，不会有错

> 我不认为这是个 bug
> 
> `php think` 命令都是在根目录下执行的。
> 
> 所以默认的路径就是在根目录，如果要访问public内容，得加上 public
> 
> 例子中里加上 public 即可访问到图片。
> 
> ```
> public function download()
> {
>     return download('public/image.jpg', 'my.jpg')->force(false);
> }
> ```
> 
> 为什么在 php think run 里能直接访问，不需要 public 路径呢，看代码：
> 
> ```
>     public function execute(Input $input, Output $output)
>     {
>         $host = $input->getOption('host');
>         $port = $input->getOption('port');
>         $root = $input->getOption('root');
>         if (empty($root)) {
>             $root = $this->app->getRootPath() . 'public';
>         }
> 
>         $command = sprintf(
>             'php -S %s:%d -t %s %s',
>             $host,
>             $port,
>             escapeshellarg($root),
>             escapeshellarg($root . DIRECTORY_SEPARATOR . 'router.php')
>         );
> 
>         $output->writeln(sprintf('ThinkPHP Development server is started On <http://%s:%s/>', '0.0.0.0' == $host ? '127.0.0.1' : $host, $port));
>         $output->writeln(sprintf('You can exit with <info>`CTRL-C`</info>'));
>         $output->writeln(sprintf('Document root is: %s', $root));
>         passthru($command);
>     }
> ```
> 
> 在执行 `php -S` 命令时，加了参数，而这里 $root 指定了 public。
> 
> 所以为了适配 think-swoole，只需在路径上加上 public 即可。

事实上，我使用：
```php
public function download()
{
    return download(public_path() . 'image.jpg', 'my.jpg')->force(false);
}
```
路径是绝对路径，不会有错

**Comment by HyperLife1119** [comment]
> 我不认为这是个 bug
> 
> `php think` 命令都是在根目录下执行的。
> 
> 所以默认的路径就是在根目录，如果要访问public内容，得加上 public
> 
> 例子中里加上 public 即可访问到图片。
> 
> ```
> public function download()
> {
>     return download('public/image.jpg', 'my.jpg')->force(false);
> }
> ```
> 
> 为什么在 php think run 里能直接访问，不需要 public 路径呢，看代码：
> 
> ```
>     public function execute(Input $input, Output $output)
>     {
>         $host = $input->getOption('host');
>         $port = $input->getOption('port');
>         $root = $input->getOption('root');
>         if (empty($root)) {
>             $root = $this->app->getRootPath() . 'public';
>         }
> 
>         $command = sprintf(
>             'php -S %s:%d -t %s %s',
>             $host,
>             $port,
>             escapeshellarg($root),
>             escapeshellarg($root . DIRECTORY_SEPARATOR . 'router.php')
>         );
> 
>         $output->writeln(sprintf('ThinkPHP Development server is started On <http://%s:%s/>', '0.0.0.0' == $host ? '127.0.0.1' : $host, $port));
>         $output->writeln(sprintf('You can exit with <info>`CTRL-C`</info>'));
>         $output->writeln(sprintf('Document root is: %s', $root));
>         passthru($command);
>     }
> ```
> 
> 在执行 `php -S` 命令时，加了参数，而这里 $root 指定了 public。
> 
> 所以为了适配 think-swoole，只需在路径上加上 public 即可。

事实上，我使用：
```php
public function download()
{
    return download(public_path() . 'image.jpg', 'my.jpg')->force(false);
}
```
路径是绝对路径，不会有错

**Comment by OverNaive** [comment]
> > 我不认为这是个 bug
> > `php think` 命令都是在根目录下执行的。
> > 所以默认的路径就是在根目录，如果要访问public内容，得加上 public
> > 例子中里加上 public 即可访问到图片。
> > ```
> > public function download()
> > {
> >     return download('public/image.jpg', 'my.jpg')->force(false);
> > }
> > ```
> > 
> > 
> > 为什么在 php think run 里能直接访问，不需要 public 路径呢，看代码：
> > ```
> >     public function execute(Input $input, Output $output)
> >     {
> >         $host = $input->getOption('host');
> >         $port = $input->getOption('port');
> >         $root = $input->getOption('root');
> >         if (empty($root)) {
> >             $root = $this->app->getRootPath() . 'public';
> >         }
> > 
> >         $command = sprintf(
> >             'php -S %s:%d -t %s %s',
> >             $host,
> >             $port,
> >             escapeshellarg($root),
> >             escapeshellarg($root . DIRECTORY_SEPARATOR . 'router.php')
> >         );
> > 
> >         $output->writeln(sprintf('ThinkPHP Development server is started On <http://%s:%s/>', '0.0.0.0' == $host ? '127.0.0.1' : $host, $port));
> >         $output->writeln(sprintf('You can exit with <info>`CTRL-C`</info>'));
> >         $output->writeln(sprintf('Document root is: %s', $root));
> >         passthru($command);
> >     }
> > ```
> > 
> > 
> > 在执行 `php -S` 命令时，加了参数，而这里 $root 指定了 public。
> > 所以为了适配 think-swoole，只需在路径上加上 public 即可。
> 
> 事实上，我使用：
> 
> ```
> public function download()
> {
>     return download(public_path() . 'image.jpg', 'my.jpg')->force(false);
> }
> ```
> 
> 路径是绝对路径，不会有错

使用绝对路径应该是最保险的方式了。

**Comment by HyperLife1119** [comment]
> 绝对路径

**Comment by HyperLife1119** [comment]
使用绝对路径，也会有上述问题

**Comment by OverNaive** [comment]
如果绝对路径有问题，那就是 @sy-records 大神说的那个 bug 了。

不过我本地测试没复现到。（绝对路径与相对路径都正常访问到）

mac os big sur 11.2.2

swoole 扩展如下：
```
$ php --ri swoole

swoole

Swoole => enabled
Author => Swoole Team <team@swoole.com>
Version => 4.6.3
Built => Feb 18 2021 00:24:42
coroutine => enabled with boost asm context
kqueue => enabled
rwlock => enabled
openssl => OpenSSL 1.1.1i  8 Dec 2020
dtls => enabled
json => enabled
curl-native => enabled
pcre => enabled
zlib => 1.2.11
brotli => E16777225/D16777225
async_redis => enabled

Directive => Local Value => Master Value
swoole.enable_coroutine => On => On
swoole.enable_library => On => On
swoole.enable_preemptive_scheduler => Off => Off
swoole.display_errors => On => On
swoole.use_shortname => On => On
swoole.unixsock_buffer_size => 262144 => 262144
```

**Comment by OverNaive** [comment]
> 如果绝对路径有问题，那就是 @sy-records 大神说的那个 bug 了。
> 
> 不过我本地测试没复现到。（绝对路径与相对路径都正常访问到）
> 
> mac os big sur 11.2.2
> 
> swoole 扩展如下：
> 
> ```
> $ php --ri swoole
> 
> swoole
> 
> Swoole => enabled
> Author => Swoole Team <team@swoole.com>
> Version => 4.6.3
> Built => Feb 18 2021 00:24:42
> coroutine => enabled with boost asm context
> kqueue => enabled
> rwlock => enabled
> openssl => OpenSSL 1.1.1i  8 Dec 2020
> dtls => enabled
> json => enabled
> curl-native => enabled
> pcre => enabled
> zlib => 1.2.11
> brotli => E16777225/D16777225
> async_redis => enabled
> 
> Directive => Local Value => Master Value
> swoole.enable_coroutine => On => On
> swoole.enable_library => On => On
> swoole.enable_preemptive_scheduler => Off => Off
> swoole.display_errors => On => On
> swoole.use_shortname => On => On
> swoole.unixsock_buffer_size => 262144 => 262144
> ```

也在 server.options 里加上了 'http_compression' => true,

**Comment by HyperLife1119** [comment]
我的swoole.server配置如下
```php
'server'     => [
        'host'      => env('SWOOLE_HOST', '0.0.0.0'), // 监听地址
        'port'      => env('SWOOLE_PORT', 9501), // 监听端口
        'mode'      => SWOOLE_PROCESS, // 运行模式 默认为SWOOLE_PROCESS
        'sock_type' => SWOOLE_SOCK_TCP, // sock type 默认为SWOOLE_SOCK_TCP
        'options'   => [
            'pid_file'              => runtime_path() . 'swoole.pid',
            'log_file'              => runtime_path() . 'swoole.log',
            'daemonize'             => !env('APP_DEBUG', false),
            // Normally this value should be 1~4 times larger according to your cpu cores.
            'reactor_num'           => swoole_cpu_num() * 2,
            'worker_num'            => swoole_cpu_num() * 2,
            'task_worker_num'       => swoole_cpu_num(),
            'enable_static_handler' => true,
            'document_root'         => public_path(),
            'package_max_length'    => 20 * 1024 * 1024,
            'buffer_output_size'    => 10 * 1024 * 1024,
            'socket_buffer_size'    => 128 * 1024 * 1024
        ],
    ],
```

**Comment by HyperLife1119** [comment]
```
php --ri swoole

swoole

Swoole => enabled
Author => Swoole Team <team@swoole.com>
Version => 4.5.9
Built => Jan 21 2021 22:10:03
coroutine => enabled
epoll => enabled
eventfd => enabled
signalfd => enabled
cpu_affinity => enabled
spinlock => enabled
rwlock => enabled
sockets => enabled
openssl => OpenSSL 1.0.2r  26 Feb 2019
pcre => enabled
zlib => 1.2.11
mutex_timedlock => enabled
pthread_barrier => enabled
futex => enabled
async_redis => enabled

Directive => Local Value => Master Value
swoole.enable_coroutine => On => On
swoole.enable_library => On => On
swoole.enable_preemptive_scheduler => Off => Off
swoole.display_errors => On => On
swoole.use_shortname => On => On
swoole.unixsock_buffer_size => 8388608 => 8388608
```

**Comment by sy-records** [comment]
我这边测试只有4.6.3 有问题，4.5是没问题的 @HyperLife1119

**Comment by HyperLife1119** [comment]
> 我这边测试只有4.6.x有问题，4.5是没问题的 @HyperLife1119

我的系统是 `Ubuntu 18.04.4 LTS`

**Comment by yunwuxin** [comment]
我这里测试 4.6.1下也是没问题的
