### ISSUE TITLE
使用go()方法时  调用request()方法获取不到任何值

### ISSUE THREAD

**Issue by ZhangTianyi-1998** [top-think/think-swoole#225]
![image](https://user-images.githubusercontent.com/37682379/111115419-8dc93480-859f-11eb-809e-6e96747b91fe.png)

![image](https://user-images.githubusercontent.com/37682379/111115545-b8b38880-859f-11eb-804d-aa9e93f2fb99.png)

需要传递外层的request实例么

**Comment by yunwuxin** [comment]
不要用go方法   go方法会导致协程id变化  获取不到当前请求的app对象了

自动协程的  没必要使用go方法

**Comment by ZhangTianyi-1998** [comment]
是这样的 我那个方法里面有多次写入
类似于
$mode1->save()
$mode2->save()
$mode3->save()

自动协程会把上面的三个写入操作协程化嘛

**Comment by yunwuxin** [comment]
会的
