### ISSUE TITLE
使用 `\Swoole\Timer::tick()` 后无法正常停止应用程序

### ISSUE THREAD

**Issue by HyperLife1119** [top-think/think-swoole#237]
问题复现：
监听 `swoole.start` 事件，在事件处理方法内使用 `Timer::tick()` 创建定时器，
然后在命令行执行 `php think swoole stop`，提示`Unable to stop the swoole_http_server process`

我需要自己在程序stop时去关闭这个tick定时器吗？
swoole文档上又说 `Worker 进程结束运行后，所有定时器都会自动销毁`

**Comment by sy-records** [comment]
文档说的是`Worker`进程，而你是在`start`的时候，不是在`workerStart`。

如果你不在`workerExit`中清除定时器的话，可以设置以下两个配置项来让Swoole处理。

```php
'reload_async' => true,
'max_wait_time' => 5,
```

https://wiki.swoole.com/#/question/use?id=swoole%e5%a6%82%e4%bd%95%e6%ad%a3%e7%a1%ae%e7%9a%84%e9%87%8d%e5%90%af%e6%9c%8d%e5%8a%a1
