### ISSUE TITLE
Declaration of think\swoole\App::runningInConsole() must be compatible with think\App::runningInConsole()

### ISSUE THREAD

**Issue by bobojx** [top-think/think-swoole#238]
thinkphp6.08安装think-swoole3.1.2之后，启动就出现这个问题，翻译过来的意思就是：think \ swoole \ App :: runningInConsole（）的声明必须与think \ App :: runningInConsole（）兼容，难道不兼容就发布为正式版本吗？希望有人回复一下这个问题

**Comment by yunwuxin** [comment]
用开发版  这个是框架最近更新了   think-swoole的提交还没有release
