### ISSUE TITLE
腾讯微服务框架里的swoole 环境 突然不能跑了,更新了什么吗

### ISSUE THREAD

**Issue by zhouyouth** [top-think/think-swoole#240]
PHP Fatal error: Declaration of think\swoole\App::runningInConsole() must be compatible with think\App::runningInConsole(): bool in /data/tars/tarsnode-data/PHP.tp6/bin/src/vendor/topthink/think-swoole/src/App.php on line 9
--
  | PHP Fatal error: Uncaught Swoole\Error: API must be called in the coroutine in /data/tars/tarsnode-data/PHP.tp6/bin/src/vendor/topthink/framework/src/think/console/output/driver/Console.php:203

**Comment by yunwuxin** [comment]
https://github.com/top-think/think-swoole/issues/238#issuecomment-835396936

**Comment by HyperLife1119** [comment]
升级think-swoole到3.0-dev开发版本
