### ISSUE TITLE
thinkphp-v6.0.8 think-swoole-v3.1.2 启动报错

### ISSUE THREAD

**Issue by a5635268** [top-think/think-swoole#241]
PHP Fatal error:  Declaration of think\swoole\App::runningInConsole() must be compatible with think\App::runningInConsole(): bool in /www/wwwroot/tianqi-api/vendor/topthink/think-swoole/src/App.php on line 18
PHP Fatal error:  Uncaught Swoole\Error: API must be called in the coroutine in /www/wwwroot/tianqi-api/vendor/topthink/framework/src/think/console/output/driver/Console.php:203

**Comment by sy-records** [comment]
https://github.com/top-think/think-swoole/issues/238#issuecomment-835396936
