### ISSUE TITLE
unable to allocate memory  

### ISSUE THREAD

**Issue by nv4010** [top-think/think-swoole#243]
unable to allocate memory

**Comment by sy-records** [comment]
see https://wiki.swoole.com/#/memory/table?id=__construct

**Comment by nv4010** [comment]
应该是改哪个参数？
'room_rows'   => 4096,
  'room_size'   => 2048*8,
  'client_rows' => 8192*8,
  'client_size' => 2048*8,
是对应的这个吗

**Comment by sy-records** [comment]
https://github.com/top-think/think-swoole/blob/e3dc88712a59c399d9990a64071eb468731287f3/src/websocket/room/Table.php#L157-L172

**Comment by nv4010** [comment]
谢谢
