### ISSUE TITLE
 HP Fatal error:  Uncaught Swoole\Error: Socket#202 has already been bound to another coroutine#3, reading of the same socket in coroutine#4 at the same time is not allowed in /www/wwwroot//tp/vendor/topthink/framework/src/think/cache/driver/Redis.php:116

### ISSUE THREAD

**Issue by nv4010** [top-think/think-swoole#246]
HP Fatal error:  Uncaught Swoole\Error: Socket#202 has already been bound to another coroutine#3, reading of the same socket in coroutine#4 at the same time is not allowed in /www/wwwroot//tp/vendor/topthink/framework/src/think/cache/driver/Redis.php:116

**Comment by yunwuxin** [comment]
注意不要长期持有连接池中的连接

**Comment by laojiang8090** [comment]
高并发都会出现这种情况，应该怎么优化呢
