### ISSUE TITLE
The app object has not been initialized

### ISSUE THREAD

**Issue by ZhangTianyi-1998** [top-think/think-swoole#249]
think-swoole 版本 3.1.3
think-orm 版本 2.0.40
framework 版本 6.0.8

PHP Fatal error:  Uncaught InvalidArgumentException: The app object has not been initialized in /mnt/c/Users/zhang/PhpstormProjects/national_health/vendor/topthink/think-swoole/src/Sandb
ox.php:135
Stack trace:
#0 /mnt/c/Users/zhang/PhpstormProjects/national_health/vendor/topthink/think-swoole/src/Sandbox.php(69): think\swoole\Sandbox->getApplication()
#1 /mnt/c/Users/zhang/PhpstormProjects/national_health/vendor/topthink/framework/src/think/Container.php(72): think\swoole\Sandbox->think\swoole\{closure}()
#2 /mnt/c/Users/zhang/PhpstormProjects/national_health/vendor/topthink/framework/src/think/Facade.php(47): think\Container::getInstance()
#3 /mnt/c/Users/zhang/PhpstormProjects/national_health/vendor/topthink/framework/src/think/Facade.php(96): think\Facade::createFacade()
#4 /mnt/c/Users/zhang/PhpstormProjects/national_health/app/model/acquisitionTerminal_v1/EmployeeModel.php(17): think\Facade::__callStatic('store', Array)
#5 /mnt/c/Users/zhang/PhpstormProjects/national_health/app/controller/acquisitionTerminal_v1/GradeUploa in /mnt/c/Users/zhang/PhpstormProjects/national_health/vendor/topthink/think-swool
e/src/Sandbox.php on line 135

[think\exception\ErrorException]
Uncaught InvalidArgumentException: The app object has not been initialized in /mnt/c/Users/zhang/PhpstormProjects/national_health/vendor/topthink/think-swoole/src/Sandbox.php:135
Stack trace:
#0 /mnt/c/Users/zhang/PhpstormProjects/national_health/vendor/topthink/think-swoole/src/Sandbox.php(69): think\swoole\Sandbox->getApplication()
#1 /mnt/c/Users/zhang/PhpstormProjects/national_health/vendor/topthink/framework/src/think/Container.php(72): think\swoole\Sandbox->think\swoole\{closure}()
#2 /mnt/c/Users/zhang/PhpstormProjects/national_health/vendor/topthink/framework/src/think/Facade.php(47): think\Container::getInstance()
#3 /mnt/c/Users/zhang/PhpstormProjects/national_health/vendor/topthink/framework/src/think/Facade.php(96): think\Facade::createFacade()
#4 /mnt/c/Users/zhang/PhpstormProjects/national_health/app/model/acquisitionTerminal_v1/EmployeeModel.php(17): think\Facade::__callStatic('store', Array)
#5 /mnt/c/Users/zhang/PhpstormProjects/national_health/app/controller/acquisitionTerminal_v1/GradeUploa

Exception trace:
() at /mnt/c/Users/zhang/PhpstormProjects/national_health/vendor/topthink/think-swoole/src/Sandbox.php:135
think\initializer\Error->appShutdown() at n/a:n/a

PHP Fatal error:  Uncaught InvalidArgumentException: The app object has not been initialized in /mnt/c/Users/zhang/PhpstormProjects/national_health/vendor/topthink/think-swoole/src/Sandb
ox.php:135
Stack trace:
#0 /mnt/c/Users/zhang/PhpstormProjects/national_health/vendor/topthink/think-swoole/src/Sandbox.php(69): think\swoole\Sandbox->getApplication()
#1 /mnt/c/Users/zhang/PhpstormProjects/national_health/vendor/topthink/framework/src/think/Container.php(72): think\swoole\Sandbox->think\swoole\{closure}()
#2 /mnt/c/Users/zhang/PhpstormProjects/national_health/vendor/topthink/framework/src/think/Facade.php(47): think\Container::getInstance()
#3 /mnt/c/Users/zhang/PhpstormProjects/national_health/vendor/topthink/framework/src/think/Facade.php(96): think\Facade::createFacade()
#4 /mnt/c/Users/zhang/PhpstormProjects/national_health/vendor/topthink/framework/src/tpl/think_exception.tpl(299): think\Facade::__callStatic('isDebug', Array)
#5 /mnt/c/Users/zhang/PhpstormProjects/national_health/vendor/topthink/framework/src/think/except in /mnt/c/Users/zhang/PhpstormProjects/national_health/vendor/topthink/think-swoole/src/
Sandbox.php on line 135

**Comment by yunwuxin** [comment]
这个是因为你自己创建了子协程，不需要自己创建协程的
