### ISSUE TITLE
如何全局获取HTTP 服务启动后的  $server 对象

### ISSUE THREAD

**Issue by sevend93** [top-think/think-swoole#25]
如何全局获取HTTP 服务启动后的  $server 对象。

例如想在控制器里面投递异步的task 任务，需要通过$sever 来投递。

**Comment by sevend93** [comment]
https://github.com/top-think/think-swoole/pull/24#issue-209358507
有人写了，麻烦有空合并下呗

**Comment by liu21st** [comment]
那个PR暂时还不能合并 我提交了一个更新 把swoole server 放入容器中了 可以很方便的读取。
