### ISSUE TITLE
请教 当开启连接池时事务处理的问题

### ISSUE THREAD

**Issue by ZhangTianyi-1998** [top-think/think-swoole#253]
我在一个方法里面调用两个model

Db::startTrans();
(new E1Model())->import($request, $companyId);
(new E2Model())->import($request, $companyId);
Db::rollback();//这个回滚不生效(连接池关闭时是好用的)
怎么能让这个事务生效呢

**Comment by yunwuxin** [comment]
我这里测试正常，如果一直可以重现的话，可以附上完整的demo
