### ISSUE TITLE
修改swoole配置文件，连接池pool数量，重启后不变

### ISSUE THREAD

**Issue by HatsuneMinami** [top-think/think-swoole#261]
swoole 4.6.4
think-swoole 4.3
swoole.php修改
//连接池
    'pool'       => [
        'db'    => [
            'enable'        => false,
            'max_active'    => 6,
            'max_wait_time' => 2,
        ],
    ],
supervisor重启运行后，还是之前的链接数量和超时时间
不知道是不是配置在闭包里，没有重新读取

**Comment by yunwuxin** [comment]
没有发现此问题
