### ISSUE TITLE
RPC服务端查询MySQL，速度慢一倍

### ISSUE THREAD

**Issue by HatsuneMinami** [top-think/think-swoole#267]
tp框架db，swoole启动的Http查询sql,比访问RPC服务方法，用db方法查询同样sql，慢一倍，
mysql表192w条，一次查询10w，RPC传输数据每秒数据量多少？能设置大些吗？目前测试RPC传输100m数据要3秒多

**Comment by yunwuxin** [comment]
使用rpc 多一次网络传输，还会经过序列化和反序列化(这个目前默认的是json，可以自己实现其他的序列化方式，并压缩)  肯定比直接查库慢

**Comment by HatsuneMinami** [comment]
就是控制器方法里用db查询同一条sql(php-fpm,swoole)，Rpc方法里也用db查询同一条sql，打印执行sql时间,(mysql表192w条，一次查询10w)，慢一倍。而且使用模型查询更慢。
