### ISSUE TITLE
Session.php中由于会莫名遇到Cookie类已被使用

### ISSUE THREAD

**Issue by f39516046** [top-think/think-swoole#27]
use think\facade\Cookie;

里边的方法在调用的Cookie的时候提示 已被占用。  具体产生原因比较模糊，有时候重新 php think swoole的时候就产生了这个问题。 改了别名后可正常使用了
use think\facade\Cookie as ThinkCookie; 然后替换掉Cookie类

**Comment by liu21st** [comment]
改进了下 感谢反馈
