### ISSUE TITLE
Tpinkphp V6.0.9 Swoole V4.7.1 连接池问题 PHP版本V8.0.10

### ISSUE THREAD

**Issue by AiMuC** [top-think/think-swoole#272]
Borrow the connection timeout in 5.00(s), connections in pool: 0, all connections: 3
Mysql/Redis连接池超过超过3个连接 不会复用之前的连接

正常访问输出'Hello ThinkPHP6'; 也会出现该问题

public function index()
{
return 'Hello ThinkPHP6';
}

**Comment by AiMuC** [comment]
好像发现问题了 使用的是Hyperf的Docker运行的
Directive => Local Value => Master Value
swoole.enable_coroutine => On => On
swoole.enable_library => On => On
swoole.enable_preemptive_scheduler => Off => Off
swoole.display_errors => On => On
swoole.use_shortname => Off => Off
关闭了短名 暂时不清楚是不是这个原因...

**Comment by AiMuC** [comment]
Directive => Local Value => Master Value
swoole.enable_coroutine => On => On
swoole.enable_library => On => On
swoole.enable_preemptive_scheduler => Off => Off
swoole.display_errors => On => On
swoole.use_shortname => On => On
swoole.unixsock_buffer_size => 8388608 => 8388608
6e8422dd6966:/home/tp6# 

在配置文件中开启后运行仍然报该问题

Borrow the connection timeout in 5.00(s), connections in pool: 0, all connections: 3
        if ($this->pool->isEmpty()) {
            // Create more connections
            if ($this->connectionCount < $this->maxActive) {
                return $this->createConnection();
            }
        }

        $connection = $this->pool->pop($this->maxWaitTime);
        if ($connection === false) {
            $exception = new BorrowConnectionTimeoutException(sprintf(
                'Borrow the connection timeout in %.2f(s), connections in pool: %d, all connections: %d',
                $this->maxWaitTime,
                $this->pool->length(),
                $this->connectionCount
            ));
            $exception->setTimeout($this->maxWaitTime);
            throw $exception;
        }
        if ($this->connector->isConnected($connection)) {

**Comment by yunwuxin** [comment]
使用最新的dev版本

**Comment by AiMuC** [comment]
重新安装dev版本后仍然存在该问题

**Comment by AiMuC** [comment]
配置全是默认都未更改的 

刷新三次网页后第四次弹出报错

Borrow the connection timeout in 5.00(s), connections in pool: 0, all connections: 3

'pool'       => [
        'db'    => [
            'enable'        => true,
            'max_active'    => 3,
            'max_wait_time' => 5,
        ],
        'cache' => [
            'enable'        => true,
            'max_active'    => 3,
            'max_wait_time' => 5,
        ],
        //自定义连接池
    ],

**Comment by yunwuxin** [comment]
那你需要检查下  你怎么使用的连接池    
按照你说的  只是 return 'Hello ThinkPHP6';

并不会使用到连接池

**Comment by AiMuC** [comment]
return 'Hello ThinkPHP6'; 和 新建模型输出数据库内容都会出现这个问题

和QQ群内一个老哥的问题是一致的  现在那个文件还在群文件里面

**Comment by yunwuxin** [comment]
不一致  群里的那个问题，是经过了查询   而且最新版本已经解决了
