### ISSUE TITLE
Swoole\Table::set(): failed to set('1879770'), unable to allocate memory

### ISSUE THREAD

**Issue by nv4010** [top-think/think-swoole#273]
Swoole\Table::set(): failed to set('1879770'), unable to allocate memory

'options'   => [
            'pid_file'              => runtime_path() . 'swoole.pid',
            'log_file'              => runtime_path() . 'swoole.log',
            'daemonize'             => true, //如果需要使用守护进程方式运行，可以配置
            // Normally this value should be 1~4 times larger according to your cpu cores.
            'reactor_num'           => swoole_cpu_num(),
            'worker_num'            => swoole_cpu_num(),
            'task_worker_num'       => swoole_cpu_num(),
            'enable_static_handler' => true,
            'document_root'         => root_path('public'),
            'package_max_length'    => 20 * 1024 * 1024,
            'buffer_output_size'    => 10 * 1024 * 1024,
            'socket_buffer_size'    => 128 * 1024 * 1024,
            'heartbeat_check_interval' => 60*60, //秒
            'reload_async'=>true,
            // 'open_websocket_ping_frame' => true,
        ],

'enable'        => true,
        'handler'       => Handler::class,
        'parser'        => Parser::class, //自定义解析类
        'ping_interval' => 25000,
        'ping_timeout'  => 60000,
        'auto_reload'      => true,
        'enable_coroutine' => true,
        'backlog'=>1280*32,
        'room'          => [
            'type'  => 'table',
            'table' => [
                'room_rows'   => 131072,
                'room_size'   => 131072*8,
                'client_rows' => 131072*8,
                'client_size' => 131072*8,
            ],

**Comment by yunwuxin** [comment]
最新版已修正
