### ISSUE TITLE
使用download方法下载文件 一直下载不结束 速度0kb

### ISSUE THREAD

**Issue by ZhangTianyi-1998** [top-think/think-swoole#275]
![image](https://user-images.githubusercontent.com/37682379/137961774-795b409c-c6c9-4fce-938e-f97b290e0377.png)
` return download($info['data']['path'], $info['data']['name'])->force(true);`

文件只要打过8kb就能下载 小于的就不行 

think-swoole v3.1.2
topthink/framework 6.0.7
nginx 1.18
php 7.4
swoole 4.8.0

**Comment by HyperLife1119** [comment]
config/swoole.php

配置文件里试试加上这个

```php
'http' => [
    // ...
    'options' => [
        'http_compression' => false
    ]
]
```
