### ISSUE TITLE
config/swoole/websocket/listener 只能写死key值 event

### ISSUE THREAD

**Issue by Sky9th** [top-think/think-swoole#287]
https://github.com/top-think/think-swoole/pull/286

**Comment by Sky9th** [comment]
![image](https://user-images.githubusercontent.com/24260942/147947123-31dc64f1-2bd4-4563-bae8-edd71253a10a.png)

![image](https://user-images.githubusercontent.com/24260942/147946801-df29b9fa-8da5-4b88-872a-0bc300058773.png)

前端emit也必须首字母大写，即便config里面首字母小写但也会在调用过程中处理成首字母大写

![image](https://user-images.githubusercontent.com/24260942/147946897-da624cba-0a07-44dc-9bca-0ef3c555e77d.png)

![image](https://user-images.githubusercontent.com/24260942/147946943-8a9750c4-baf7-4260-8528-c2aee31217e9.png)

即便文档来不及做，是不是也能够上传个demo到git里面

**Comment by Sky9th** [comment]
即便文档来不及做，是不是也能够上传个demo到git里面

**Comment by HyperLife1119** [comment]
https://www.jianshu.com/p/568f1064b70a

**Comment by Sky9th** [comment]
@HyperLife1119 也是一种解决方案

**Comment by yunwuxin** [comment]
这里统一分发到`swoole.websocket.Event`事件，是为了防止自定义事件和内置事件冲突，可以在`swoole.websocket.Event`事件里再自行分发处理，或者自定义一个handler
