### ISSUE TITLE
中间件失效的问题

### ISSUE THREAD

**Issue by sevend93** [top-think/think-swoole#29]
使用的 group路由 添加的中间件
swoole 模式下，我这里测试中间件拦截失效

中间件部分我设置

public function handle($request, \Closure $next)
{
return response()->data('xxx');
}

第一次拦截成功返回xxx
第二次不拦截直接执行后续的方法
第三次拦截成功返回xxx
第四次不拦截直接执行后续的方法

一直这样循环

**Comment by liu21st** [comment]
已经修正了

**Comment by yumufeng** [comment]
> 已经修正了

用的最新版本 2.0-dev的swoole和5.1.x-dev的内核，依然有问题。只加载一次，中间件就不加载了。
继承Controller后，数据只能获取一次。

**Comment by yumufeng** [comment]
// 清除中间件数据
            $this->middleware->clear(); 
压根就没有用啊,swoole版本 4.2.1
