### ISSUE TITLE
Service.php 中函数参数多了一个逗号

### ISSUE THREAD

**Issue by aweihaitun** [top-think/think-swoole#290]
D:\www\metastar\vendor\topthink\think-swoole\src\Service.php line 25

**Comment by yunwuxin** [comment]
没有影响

**Comment by aweihaitun** [comment]
因为我本地安装了think-swoole以后报错了，不然我这边也不会发现这个问题，多余的逗号删除以后就没有错误了，环境为PHP7.2，我看到之前的代码，最后一个参数后面都是没有逗号的，麻烦再看一下

**Comment by yunwuxin** [comment]
composer.php 已经要求了 php>=7.4

**Comment by aweihaitun** [comment]
谢谢回复，没注意到这个限制
