### ISSUE TITLE
swoole 上传文件

### ISSUE THREAD

**Issue by Mr-ZhongWeiWei** [top-think/think-swoole#294]
上传文件就超时WARNING	Worker_reactor_try_to_exit() (ERRNO 9101): worker exit timeout, forced termination
什么原因导致上传base64图片超时 检查过了naginx、php、package_max_length配置都没有问题

**Comment by yunwuxin** [comment]
无法重现

**Comment by Mr-ZhongWeiWei** [comment]
@yunwuxin 已解决 wsl环境版本的问题
