### ISSUE TITLE
多应用TP下，在服务中定义路由导致第一次访问会报错

### ISSUE THREAD

**Issue by rocky-git** [top-think/think-swoole#296]
先服务中定义路由，然后第一次返回就会报错
![image](https://user-images.githubusercontent.com/44958386/154399920-52c579e1-fa43-4a55-8dab-ac49a48a4c0b.png)
原因是预先初始了route进去的app和后面app不一致导致

暂时自己的解决方案是定义中间件修改route中的app，截图如下：
![image](https://user-images.githubusercontent.com/44958386/154400286-f0b435dc-e148-401b-b62a-aa63b8e1ed14.png)

**Comment by HyperLife1119** [comment]
不支持多应用

**Comment by yunwuxin** [comment]
不支持多应用
而且有需要在服务中定义路由的请在服务中注册RouteLoaded事件监听 在这个事件里定义路由
