### ISSUE TITLE
新安装的服务端 Html5的Websocket测试 可以连接成功，发送消息就立马断开或等待也会自动断开

### ISSUE THREAD

**Issue by New-Zero-Zero** [top-think/think-swoole#299]
宝塔版本
7.9.0
php7.4版本（通过宝塔的面板的安装）
7.4.28
redis版本（通过宝塔的面板的扩展库安装）
5.3.4
php think 版本 
6.0.8
swoole 版本(通过宝塔面板的扩展库安装的)
4.8.5
think-swoole版本
  - Downloading nette/utils (v3.2.7)
  - Downloading symfony/deprecation-contracts (v2.5.0)
  - Downloading symfony/finder (v5.4.3)
  - Downloading swoole/ide-helper (4.8.7)
  - Downloading stechstudio/backoff (1.2)
  - Downloading open-smf/connection-pool (v1.0.16)
  - Downloading nette/php-generator (v3.6.6)
  - Downloading topthink/think-swoole (v4.0.7)
  - Installing nette/utils (v3.2.7): Extracting archive
  - Installing symfony/deprecation-contracts (v2.5.0): Extracting archive
  - Installing symfony/finder (v5.4.3): Extracting archive
  - Installing swoole/ide-helper (4.8.7): Extracting archive
  - Installing stechstudio/backoff (1.2): Extracting archive
  - Installing open-smf/connection-pool (v1.0.16): Extracting archive
  - Installing nette/php-generator (v3.6.6): Extracting archive
  - Installing topthink/think-swoole (v4.0.7): Extracting archive
![image](https://user-images.githubusercontent.com/32284859/159888723-289fc35b-7e28-4506-8acb-b4043cb4f398.png)

**Comment by yunwuxin** [comment]
默认是socket.io驱动

**Comment by New-Zero-Zero** [comment]
> 

没懂啊，是要改啥配置文件么？

**Comment by yunwuxin** [comment]
客户端要使用[socket.io](https://socket.io/)

**Comment by he426100** [comment]
@New-Zero-Zero  默认的websocket是socket.io，普通的websocket得改config/swoole，把Handler换成use think\swoole\websocket\Handler 然后弄个 WebsocketSubscribe，配置在 config/swoole:websocket.subscribe
