### ISSUE TITLE
thinkphp-v6.0.12, think-swoole-v4.0.7, php think swoole 启动报错

### ISSUE THREAD

**Issue by chengze-cc** [top-think/think-swoole#300]
thinkphp版本和think-swoole版本
<img width="873" alt="image" src="https://user-images.githubusercontent.com/43336791/160331808-6e0d34e2-5c43-4e72-8c79-c7c1dc3bf9eb.png">

swoole 版本
<img width="446" alt="image" src="https://user-images.githubusercontent.com/43336791/160332242-4a9eefb2-58b1-488c-9c1e-fb6136ad1d9c.png">

php think swoole 启动报错
`
PHP Fatal error:  Uncaught Swoole\Error: API must be called in the coroutine in /home/vagrant/Code/platform/vendor/topthink/framework/src/think/console/output/driver/Console.php:203
Stack trace:
#0 /home/vagrant/Code/platform/vendor/topthink/framework/src/think/console/output/driver/Console.php(203): proc_open()
#1 /home/vagrant/Code/platform/vendor/topthink/framework/src/think/console/output/driver/Console.php(180): think\console\output\driver\Console->getSttyColumns()
#2 /home/vagrant/Code/platform/vendor/topthink/framework/src/think/console/output/driver/Console.php(145): think\console\output\driver\Console->getTerminalDimensions()
#3 /home/vagrant/Code/platform/vendor/topthink/framework/src/think/console/output/driver/Console.php(82): think\console\output\driver\Console->getTerminalWidth()
#4 /home/vagrant/Code/platform/ve in /home/vagrant/Code/platform/vendor/topthink/framework/src/think/console/output/driver/Console.php on line 203
`

**Comment by New-Zero-Zero** [comment]
proc_open 函数在禁用列表里面

**Comment by chengze-cc** [comment]
> proc_open 函数在禁用列表里面

函数禁用列表是空的。

<img width="854" alt="image" src="https://user-images.githubusercontent.com/43336791/160578536-9095ffdf-8cf4-4a08-85e2-76787e74250a.png">

**Comment by chengze-cc** [comment]
将函数proc_open禁用。问题已解决。
