### ISSUE TITLE
tp3.2 有解决方案吗

### ISSUE THREAD

**Issue by phper-lsx** [top-think/think-swoole#31]

**Comment by xavieryang007** [comment]
不建议使用TP3.2版本 采用SWOOLE运行模式。
可以采用TP5.1，是因为现有项目采用的TP3.2？

**Comment by kajweb** [comment]
我们现在的项目是在TP3.2的中运行的，打算整体迁移到swoole

**Comment by liu21st** [comment]
没法迁移，只能重构，就算你能迁移到swoole 核心也要改的，官方目前没有5.0以下的解决方案。
