### ISSUE TITLE
经常出现这种问题，请问原因是什么？怎么解决？谢谢

### ISSUE THREAD

**Issue by iamadeveloperforit** [top-think/think-swoole#312]
[2022-08-17T13:22:00+08:00][error] [1]Uncaught InvalidArgumentException: The app object has not been initialized in /www/wwwroot/dou-dian-back/vendor/topthink/think-swoole/src/Sandbox.php:135
Stack trace:
#0 /www/wwwroot/dou-dian-back/vendor/topthink/think-swoole/src/Sandbox.php(69): think\swoole\Sandbox->getApplication()
#1 /www/wwwroot/dou-dian-back/vendor/topthink/framework/src/think/Container.php(72): think\swoole\Sandbox->think\swoole\{closure}()
#2 /www/wwwroot/dou-dian-back/vendor/topthink/framework/src/think/Facade.php(47): think\Container::getInstance()
#3 /www/wwwroot/dou-dian-back/vendor/topthink/framework/src/think/Facade.php(96): think\Facade::createFacade()
#4 /www/wwwroot/dou-dian-back/app/webscoket/SwooleWorkerStart.php(110): think\Facade::__callStatic('error', Array)
#5 {main}
  thrown[/www/wwwroot/dou-dian-back/vendor/topthink/think-swoole/src/Sandbox.php:135]

**Comment by yunwuxin** [comment]
别在业务代码里使用go创建协程

**Comment by iamadeveloperforit** [comment]
ok, thanks
