### ISSUE TITLE
4.0 Hook 问题

### ISSUE THREAD

**Issue by xionvi** [top-think/think-swoole#321]
请问
为什么不用：Runtime::enableCoroutine($flags = SWOOLE_HOOK_ALL);
而是：Runtime::enableCoroutine();
如果要Hook，该如何处理？

**Comment by yunwuxin** [comment]
默认不就是SWOOLE_HOOK_ALL

**Comment by xionvi** [comment]
在哪里默认的呢，没找到相关文档和代码？
并且这两种情况我都试过了，如果不加SWOOLE_HOOK_ALL，SWOOLE_HOOK_NATIVE_CURL就不得行，加上了就没问题呢

**Comment by sy-records** [comment]
这是Swoole的行为，如果你需要开启或者关闭某些hook，需要手动设置参数。

**Comment by xionvi** [comment]
> 

你的意思是在程序里面自己手动设置吗？
