### ISSUE TITLE
增加CommandManager以支持在command中运行

### ISSUE THREAD

**Issue by he426100** [top-think/think-swoole#331]
CommandManager.php
```
<?php
declare (strict_types = 1);

namespace think\swoole;

use think\swoole\concerns\InteractsWithPools;
use think\swoole\concerns\InteractsWithServer;
use think\swoole\concerns\InteractsWithTracing;
use think\swoole\concerns\WithApplication;
use think\swoole\concerns\WithContainer;

class CommandManager
{
    use InteractsWithServer,
        InteractsWithPools,
        InteractsWithTracing,
        WithContainer,
        WithApplication;

    /**
     * Initialize.
     */
    protected function initialize(): void
    {
        $this->preparePools();
        $this->prepareTracing();
    }
}
```

SwooleCommand.php
```
<?php
declare (strict_types = 1);

namespace think\swoole\command;

use Swoole\Constant;
use think\swoole\CommandManager;
use think\console\Command;
use think\console\Input;
use think\console\input\Argument;
use think\console\input\Option;
use think\console\Output;

abstract class Swoole extends Command
{
    protected function configure()
    {
        $this->setName('swoole command')
            ->addOption(
                'env',
                'E',
                Option::VALUE_REQUIRED,
                'Environment name',
                ''
            )
            ->setDescription('Swoole Command for ThinkPHP');
    }

    protected function execute(Input $input, Output $output)
    {
        $manager = app(CommandManager::class);
        $manager->addWorker(function () use ($input, $output) {
            $this->runInSwoole($input, $output);
        }, $this->getName());
        $envName = $this->input->getOption('env');
        $manager->start($envName);
    }

    protected abstract function runInSwoole(Input $input, Output $output);
}
```

这样就可以在协程环境下运行任意command了

**Comment by yunwuxin** [comment]
你要在command里有协程环境 直接使用run方法创建一个协程容器就可以了   
再者，在command下又不存在并发  要协程环境干嘛

**Comment by he426100** [comment]
假如做一些并发入库的操作就需要连接池了

**Comment by lait233** [comment]
在command里面使用协程操作数据怎么样保证mysql链接是独立的？链接池怎么配呢？

**Comment by he426100** [comment]
> 在command里面使用协程操作数据怎么样保证mysql链接是独立的？链接池怎么配呢？

command和http里面操作数据库是一样的，不用特别配置，http下可以command下就可以

**Comment by lait233** [comment]
@he426100 我在多个协程同时用model去查询 或者插入数据就会报错 提醒不同协程不能用同一个连接了。你是怎么解决的呢？用扩展里面的Db类吗。 因为我很多东西在model里面要完成。。。所以不能用Db类的连接池

**Comment by he426100** [comment]
> @he426100 我在多个协程同时用model去查询 或者插入数据就会报错 提醒不同协程不能用同一个连接了。你是怎么解决的呢？用扩展里面的Db类吗。 因为我很多东西在model里面要完成。。。所以不能用Db类的连接池

```php
<?php

declare(strict_types=1);

namespace app\command;

use app\model\Test as TestModel;
use think\facade\Db;
use think\console\Command;
use think\console\Input;
use think\console\input\Argument;
use think\console\input\Option;
use think\console\Output;
use think\swoole\command\Swoole;
use Swoole\Coroutine\WaitGroup;
use Swoole\Coroutine\Channel;
use function Swoole\Coroutine\go;

class Test extends Swoole
{
    protected function configure()
    {
        // 指令配置
        $this->setName('swoole:test')
            ->addOption(
                'env',
                'E',
                Option::VALUE_REQUIRED,
                'Environment name',
                ''
            )
            ->setDescription('the swoole test command');
    }

    protected function runInSwoole(Input $input, Output $output)
    {
        TestModel::find(1)->save(['val' => 0]);
        $wg = new WaitGroup();
        // 用channel控制并发数量，config/swoole里面配置'max_active' => 64,
        $chan = new Channel(64);
        for ($c = 10000; $c--;) {
            $wg->add();
            $chan->push(true);
            go(function () use ($wg, $chan) {
                Db::transaction(function () use ($wg, $chan) {
                    try {
                        $t = TestModel::lock(true)->find(1);
                        $t->save(['val' => $t['val'] + 1]);
                        echo TestModel::find(1)['val'], PHP_EOL;
                    } catch (\Throwable $e) {
                        echo 'error: ' . $e->getMessage(), PHP_EOL;
                    } finally {
                        $chan->pop();
                        $wg->done();
                    }
                });
            });
        }
        $wg->wait();
        echo TestModel::find(1)['val'], PHP_EOL;
        echo 'ok', PHP_EOL;
    }
}
```

**Comment by stonegithubs** [comment]
> 你要在command里有协程环境 直接使用run方法创建一个协程容器就可以了 再者，在command下又不存在并发 要协程环境干嘛
命令行中


> 你要在command里有协程环境 直接使用run方法创建一个协程容器就可以了 再者，在command下又不存在并发 要协程环境干嘛

直接run方法，遇到这样的错误，请教下有什么办法在Command中运行协程，想用于并发更新数据
PHP Fatal error:  Uncaught Swoole\Error: Socket#8 has already been bound to another coroutine#3, reading of the same socket in coroutine#6 at the same time is not allowed in /www/tp8/vendor/topthink/think-orm/src/db/PDOConnection.php:800
Stack trace:
#0 /www/tp8/vendor/topthink/think-orm/src/db/PDOConnection.php(800): PDO->prepare()
#1 /www/tp8/vendor/topthink/think-orm/src/db/PDOConnection.php(745): think\db\PDOConnection->getPDOStatement()
#2 /www/tp8/vendor/topthink/think-orm/src/db/PDOConnection.php(921): think\db\PDOConnection->pdoQuery()
#3 /www/tp8/vendor/topthink/think-orm/src/db/BaseQuery.php(1361): think\db\PDOConnection->find()

protected function execute(Input $input, Output $output)
    {
        run(function () {
            TestModel::find(1)->save(['val' => 0]);
            $wg = new WaitGroup();
            // 用channel控制并发数量，config/swoole里面配置'max_active' => 64,
            $chan = new Channel(64);
            for ($c = 10000; $c--;) {
                $wg->add();
                $chan->push(true);
                go(function () use ($wg, $chan) {
                    Db::transaction(function () use ($wg, $chan) {
                        try {
                            $t = TestModel::lock(true)->find(1);
                            $t->save(['val' => $t['val'] + 1]);
                            echo TestModel::find(1)['val'], PHP_EOL;
                        } catch (\Throwable $e) {
                            echo 'error: ' . $e->getMessage(), PHP_EOL;
                        } finally {
                            $chan->pop();
                            $wg->done();
                        }
                    });
                });
            }
            $wg->wait();
            echo TestModel::find(1)['val'], PHP_EOL;
            echo 'ok', PHP_EOL;
        });
    }
