### ISSUE TITLE
Swoole\Table::set(): failed to set('1.22008'), unable to allocate memory[/var/www/thinkphp/vendor/topthink/think-swoole/src/websocket/room/Table.php:190]

### ISSUE THREAD

**Issue by tgpx1899** [top-think/think-swoole#336]
报错：Swoole\Table::set(): failed to set('1.22008'), unable to allocate memory[/var/www/thinkphp/vendor/topthink/think-swoole/src/websocket/room/Table.php:190]，
用的php8.0，swoole4.8.11，think-swoole4.0.7，请问是什么问题

**Comment by sy-records** [comment]
如果你的数据 Key 和 Hash 冲突率超过 20%，预留的冲突内存块容量不足，set 新的数据就会报 Unable to allocate memory 错误，并返回 false，存储失败，此时需要调大 $size 值并重启服务。
