### ISSUE TITLE
swoole 服务器无法启动

### ISSUE THREAD

**Issue by sevend93** [top-think/think-swoole#34]
框架核心更新到  5.1.24 ，   swoole 更新到  2.0.x-dev b618376  

php think swoole  启动提示

  [think\exception\ThrowableError]                            
  Fatal error: Call to a member function getName() on string  
                                                              

php think swoole:server 没有问题

**Comment by liu21st** [comment]
既然你扩展是开发版，那么核心框架也更新到开发版就行了
