### ISSUE TITLE
在控制器中监听数据库事件,当这个控制器的方法被调用多次时,数据库的事件是累加触发的

### ISSUE THREAD

**Issue by haozhi6** [top-think/think-swoole#345]
php think version
v6.0.7
topthink/think-queue
v3.0.4

版本信息如上

问题如题
不止是我的使用方法有问题 还是bug问题 望解惑 谢谢

**Comment by haozhi6** [comment]
调用方式如下图 
控制器调用数据库事件监听
![image](https://github.com/top-think/think-swoole/assets/45025597/5c7fbea3-440b-4a93-81ae-788733fb193b)

问题如下图
![image](https://github.com/top-think/think-swoole/assets/45025597/bedbc4f5-b342-4de4-94c0-023ca8a3755a)

**Comment by yunwuxin** [comment]
因为你每访问一次  就会注册一个事件回调

**Comment by haozhi6** [comment]
> 因为你每访问一次 就会注册一个事件回调

我大概猜到这个原因了 我想问这算是bug, 还是如此设计,我现在使用的是model层 on(事件)方法跳过这个问题了
