### ISSUE TITLE
协程中数据库问题

### ISSUE THREAD

**Issue by wydhit** [top-think/think-swoole#35]
协程模式下，同一个worker下全局变量共享，那么数据库连接也应该是共享的，\think\Db::$connection，但是有多个协程在执行，多个协程在复用这个连接，在实际的业务逻辑中又用到了事务，不会存在冲突吗？

比如这种情况：协程A 开启事务   这个事务比较耗时  这是会执行协程B，协程B进行了一个插入操作，返回协程A  ，这时候协程A事务回滚，这样协程B的插入操作就失效了。（协程A B 执行不同的请求）
或者类似于这样的其他冲突情况。

**Comment by xavieryang007** [comment]
如果只有一个链接实例对象，那么在协程中使用事务，是会造成冲突的，可以分开事务

**Comment by wydhit** [comment]
分开事务？我觉得只能这样，比如协程B内的仅有的一个插入操作也得在事务内执行。不然就有可能被回滚，导致执行失败

**Comment by xavieryang007** [comment]
分开实例，也就是分开链接。这样A=new PDO_MYSQL  ,B=new pdo_mysql，  这样A的事务不会干扰B

**Comment by sevend93** [comment]
目前  tp-orm 还不支持协程吧，高并发下肯定会出问题。 @xavieryang007 可以做个orm 的协程改造呗，现在swoole 4.1.0 出来了

**Comment by xavieryang007** [comment]
有计划开发一个连接池，只是把他加入协程并无法彻底解决问题

**Comment by fffloong** [comment]
期待think-swoole的数据库和Redis连接池

**Comment by xavieryang007** [comment]
哈哈！正在开发中

**Comment by fffloong** [comment]
@xavieryang007  有dev版了我可以帮你测试

**Comment by xavieryang007** [comment]
好的

**Comment by fffloong** [comment]
https://github.com/louislivi/smproxy  这个看起来很不错的样子

**Comment by xavieryang007** [comment]
已经看过了 多谢
