### ISSUE TITLE
Redis连接数不断的增长，每隔十几天要重启下swoole才能降低连接数

### ISSUE THREAD

**Issue by stonegithubs** [top-think/think-swoole#358]
Redis连接数不断的增长，不重启的话，当超过最大连接就无法连接Redis，请教下有什么办法自动回收连接
主要是小程序的api请求，晚上没有api请求，连接也不会自动释放，当业务量稍微大点，每两天得重启下swoole
![redis连接](https://github.com/top-think/think-swoole/assets/11014061/06bdad73-6cc0-4071-bb0f-083baf211880)
Redis是阿里云的，最大连接10000
协程并发是不错，连接释放不了，还得实时监控Redis连接，连接满了不重启，整个与Redis有关的完全不能用，只能重启swoole，业务量再大些不敢继续用swoole

```php
//swoole连接池配置
    'pool'       => [
        'db'    => [
            'enable'        => true,
            'max_active'    => swoole_cpu_num() * 4,
            'max_wait_time' => 5,
        ],
        'cache' => [
            'enable'        => true,
            'max_active'    => 6,
            'max_wait_time' => 5,
        ],
        //自定义连接池
    ],
```

**Comment by TienYow** [comment]
我也遇到相同的问题, 使用 supervisor 启动的 think-swoole, 一段时间后就会宕机, 现在我关闭了cache 的连接池
`
    //连接池
    'pool'       => [
        'db'    => [
            'enable'        => true,
            'max_active'    => 3,
            'max_wait_time' => 5,
        ],
        'cache' => [
            'enable'        => false,
            'max_active'    => 3,
            'max_wait_time' => 5,
        ],
        //自定义连接池
    ],
    'ipc'        => [
        'type'  => 'unix_socket',
        'redis' => [
            'host'          => '127.0.0.1',
            'port'          => 6379,
            'max_active'    => 3,
            'max_wait_time' => 5,
        ],
    ],
`

**Comment by yunwuxin** [comment]
连接池本身有上限的  没释放只会不够用 不会无限制增长    检查是是否哪里自己使用了redis然后没有释放连接

**Comment by stonegithubs** [comment]
感谢回复，测试了好久没找到问题，也用别人的来测试，并发量稍微多些还是会有这样的情况，改用Rust来开发API了

**Comment by zhuyaxu** [comment]
@yunwuxin 我们也遇到了同样的问题，也检查了并没有自己使用没有释放的情况
