### ISSUE TITLE
public下的静态文件怎么处理

### ISSUE THREAD

**Issue by duchao1990** [top-think/think-swoole#365]
`http://192.168.0.103:8080/SLfp4GQZfd.txt`
```
{
    "code": 500,
    "msg": "网络繁忙,请稍后重试",
    "data": {
        "request": "SLfp4GQZfd.txt",
        "data": [],
        "file": "/www/wwwroot/userapi/vendor/topthink/framework/src/think/route/dispatch/Controller.php",
        "line": 76,
        "msg": "controller not exists:app\\controller\\SLfp4GQZfd\\Txt"
    },
    "time": 1709808639
}
```
应用场景是,微信公众号的文件校验用的,要求放到根目录里边,放在public下边但是一直会去调用控制器

**Comment by wds7788** [comment]
访问静态文件
4.0开始协程风格服务端默认不支持静态文件访问，建议使用nginx来支持静态文件访问，也可使用路由输出文件内容，下面是示例，可参照修改

添加静态文件路由：
Route::get('static/:path', function (string $path) {
    $filename = public_path() . $path;
    return new \think\swoole\response\File($filename);
})->pattern(['path' => '.*\.\w+$']);
访问路由 http://localhost/static/文件路径

**Comment by w263756314** [comment]
添加静态文件路由的方式，在访问 css 或者 js 文件时可能会因为文件类型不匹配导致加载失败，建议使用反向代理的服务把静态文件和PHP文件的访问分开，比如静态文件直接用nginx，动态文件就转发给8080端口。
比如：
`
location /
    {
        if (!-e $request_filename){
            proxy_pass http://127.0.0.1:8080;
        }
        proxy_http_version 1.1;
        proxy_read_timeout 360s;   
        proxy_redirect off; 
        proxy_set_header Host $host;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header REMOTE-HOST $remote_addr;
        proxy_buffering off; 

        add_header X-Cache $upstream_cache_status;
    }
`
