### ISSUE TITLE
在swoole中中间件失效的BUG

### ISSUE THREAD

**Issue by yumufeng** [top-think/think-swoole#37]
swoole版本：4.2.1
失效原因：
第一次访问URL到对应控制器时候，会调用中间件，第二次就不会调用了。

**失效过程，还原过如下**：

在thinkphp5中，要对某个类用中间件拦截
需要继承Controller；

![2](https://user-images.githubusercontent.com/9146937/45958113-2c1c5500-c049-11e8-9c78-14cd2a88f6b7.png)

中间件，官方在Controller控制器的处理如下：
![1](https://user-images.githubusercontent.com/9146937/45958140-39d1da80-c049-11e8-993c-399085b9642f.png)

**问题原因：**

swoole的onRequest里第一次访问url的时候，会去执行一次构造方法，再次访问的时候，就不会去执行构造方法。
因此中间件只会被执行一次，再次访问URL时候构造函数里的操作并不会被执行。

**Comment by yumufeng** [comment]
同理，通过$this->request获取的参数也不好使实时请求参数。

**Comment by browningweb** [comment]
确实如此，希望跟进。

**Comment by xavieryang007** [comment]
是否执行过$this->middleware->clear();

**Comment by fushutech** [comment]
config/swoole.php 
'max_request' => 1,

可以通过这样临时解决一下。

**Comment by xavieryang007** [comment]
正在解决这个问题，在控制器中出现这个问题是因为Container里实例了控制器，请求结束后将对应控制器删除，@fushutech 因为这样会每次请求都重新创建进程，消耗资源更大，不建议生产环境使用

**Comment by liu21st** [comment]
这个问题最新框架的开发版本 已经解决了的

**Comment by fushutech** [comment]
@liu21st 什么时间发布稳定版？

**Comment by xavieryang007** [comment]
新版本已经发布了

**Comment by fushutech** [comment]
nice！

**Comment by browningweb** [comment]
全局中间件有问题，在应用目录下面定义middleware.php文件，第一次请求可以，再刷新，就不在走全局中间件了。

`return [
    app\http\middleware\Api::class
];`

**Comment by liu21st** [comment]
@browningweb 改进了
