### ISSUE TITLE
我在用swoole5.1.2运行并开启热更新后，每次热更新都会报一个[FATAL ERROR]: all coroutines (count: 1) are asleep - deadlock!这个提示，这怎么解决

### ISSUE THREAD

**Issue by usertangxin** [top-think/think-swoole#371]
我在用swoole5.1.2运行并开启热更新后，每次热更新都会报一个[FATAL ERROR]: all coroutines (count: 1) are asleep - deadlock!这个提示，这怎么解决

**Comment by sy-records** [comment]
https://wiki.swoole.com/zh-cn/#/server/setting?id=enable_deadlock_check 设为false
