### ISSUE TITLE
文档太少了（但是通过认真阅读源码还是很有帮助的）。websocket的fd问题请大佬指点一二

### ISSUE THREAD

**Issue by note-sun** [top-think/think-swoole#379]
tp8安装的tp-swoole扩展，启用websocket后，我们在onOpen中使用webSocket实例的getSender()方法获取的fd，即使去掉小数点前的进程id，那为啥这个fd与omMessage的Frame->fd也不一样呢。

**Comment by yunwuxin** [comment]
本来就不一样  这个getSender获取到的标识 是框架自行管理的一个标识   后续发送消息也只需要这个   omMessage的Frame->fd不需要使用

**Comment by note-sun** [comment]
> 本来这个 getSender 获取到的标识是框架自行管理的一个标识后续发送消息也只需要这个 omMessage 的 Frame->fd 不需要使用

特别感谢你的指点和耐心回复。确实发现frame的fd在实际业务中用不上。 我正在学习tp-swoole的代码，分析它的启动流程和工作流程，如果有总结出来的一些经验，我会向readme.md提pr
