### ISSUE TITLE
think内核swoole分模块配置有BUG

### ISSUE THREAD

**Issue by yumufeng** [top-think/think-swoole#38]
TP版本：5.1.x-dev版本
TP-Swoole：2.0.x-dev版本

**配置BUG问题如下：**
有两个模块
默认module为：index
API的module为：api

**问题经过还原如下**
在API中建立config/app.php配置文件
目录如下/application/api/config/app.php

当我们启动swoole的时候，在onWorkerStart里会初始化读取一次配置，如下;
![7](https://user-images.githubusercontent.com/9146937/46004616-e5c90380-c0e5-11e8-9702-8e3cca767289.png)
然后去init()去读取配置 
![1](https://user-images.githubusercontent.com/9146937/46004828-6ee03a80-c0e6-11e8-9c19-07d8920d4b0b.png)
$dir = $this->configPath . $module;
在workerstart的时候已经加载到内存中没有问题。

**问题出现：**

但是当我们在api模块下，建立一个config/app.php
配置如下：
`return [
    // 默认输出类型
    'default_return_type' => 'json',
];`
访问api/index/index的时候，api模块下的配置会被重载到内存中。
此时api模块下输出的为json格式

但是我们此时切换回index/index/index的时候,当我们访问 index/index/index的时候
而此时 $dir会找不到。所以默认采用内存中上次出现的配置
此时index/index/index 本来应该采用默认配置输出html格式的。却输出了json格式。

解决方式：
在index模块下也建立一个配置，默认输出改为html

**Comment by yumufeng** [comment]
另外一种修复方式，在thinkphp/library/think/App.php中init路由加载里 再增加一行
![1](https://user-images.githubusercontent.com/9146937/46005823-b49e0280-c0e8-11e8-87b4-19dde37fa4d8.png)

这样所有的模块当没有配置的时候，默认的去加载默认配置文件

**Comment by liu21st** [comment]
每次load配置文件是合并的 并不会清空，所以你的第二个方案应该无效的，鉴于很多方面的原因，下一个TP版本计划废除模块的概念而用多应用取代
