### ISSUE TITLE
onWorderStart事件如何识别是不是热更新的worker进程

### ISSUE THREAD

**Issue by note-sun** [top-think/think-swoole#380]
有请大佬帮我指点一下，我需要再每个工作进程的onWorkerStart事件中启动一个业务上的实例，但是我发现热更新的逻辑也是通过addWorker()方法创建的worker进程，我并不想在热更新的worker中启动我的这个业务实例，所以我在时间监听onWorkerStart的代码中如何识别当前的worker是不是热更新的进程。

**Comment by yunwuxin** [comment]
WorkerStart事件返回了进程名称参数  可以通过这个来判断

**Comment by note-sun** [comment]
> WorkerStart活动返回了进程名称参数可以通过此来判断

<img width="992" alt="image" src="https://github.com/user-attachments/assets/b9d55daf-cdea-49f3-b288-b88a117913e9">
看代码发现并没有给workerstart事件传递任何参数。 我是tp-swoole v4.0.13

**Comment by yunwuxin** [comment]
最新版
