### ISSUE TITLE
ws向客户端发送消息push方法可以增加一个客户端状态监测吗

### ISSUE THREAD

**Issue by note-sun** [top-think/think-swoole#382]
不知道我的想法是否合理。
\think\swoole\Websocket->to($fd)->push(...);
这个方法可以返回发送成功与否的结果吗，例如在push之前增加swoole的exist方法。

**Comment by yunwuxin** [comment]
发送消息是异步的 不能实时返回结果

**Comment by note-sun** [comment]
> 发送消息是异步的 不能实时返回结果

嗯嗯 是异步，但是可不可以在发送之前先检测一下fd是否在线处于活动状态

**Comment by yunwuxin** [comment]
自行检查 
websocket对象有isEstablished  但只能检查当前连接的    也并不可靠   只有发送了才知道这个连接是否正常
或者使用room的getClients方法来辅助判断

**Comment by note-sun** [comment]
> 自行检查 websocket对象有isEstablished 但只能检查当前连接的 也并不可靠 只有发送了才知道这个连接是否正常 或者使用room的getClients方法来辅助判断

好的，感谢指点
