### ISSUE TITLE
【4.0.13】进程通信问题，多个worker进程时，进程通信onMessage偶尔时不时报错The app object has not been initialized

### ISSUE THREAD

**Issue by note-sun** [top-think/think-swoole#388]
我的发送方法：
```php
$manage = app(Manager::class);
$manage->sendMessage((int)$toWorkerProcessId, []);
```

我的swoole.onMessage事件处理：
```php
class OnMessage {
	public function handle($event) {
	        try{
			$gameManage = app(GameManage::class);
			dump(count($gameManage->sessionList));
		}catch (\Exception $e){
			dump($e->getMessage());
		}
	}
}
```

因为我在消息处理方法中要获取当前worker进程的容器内实例，但是总是偶尔报错app object has not been initialized。
如果worker_num = 1 ，那么毫无问题。 另外我确定我是将消息推送到了http server 进程，并不是推送到了hot update或者queue进程。

已经连续研究了接近10个小时了，扛不住，先暂时使用worker_num = 1应付上线吧，希望得到回复。

**Comment by note-sun** [comment]
我是在自定义订阅类里实现的swoole的消息订阅。

```php
use think\Event;
class Swoole {
	
	public function onInit() {
		dump('swoole init');
	}
	
	public function onWorkerStart($param) {
		dump('onWorkerStart -->> worker name >>> ' . $param . ' <<<');
		//每个worker里需要预加载以共用的实例,请在swoole配置文件中添加. 因为热更新或者task进程都会进入这方法
	}
	
	public function onStart() {
		dump('onStart');
	}
	
	public function onMessage($event) {
		
		if(is_array($event) && $event['process_msg']) {
			//进程间通信
			WorkerProcessMsg::handleProcessMsg($event);
		}
	}
	
	public function subscribe(Event $event) {
		dump($event);
		$event->listen('swoole.init', [$this, 'onInit']);
		$event->listen('swoole.workerStart', [$this, 'onWorkerStart']);
		$event->listen('swoole.start', [$this, 'onStart']);
		$event->listen('swoole.message', [$this, 'onMessage']);
	}
}
```

**Comment by note-sun** [comment]
从凌晨一点开始翻源码，搞到现在还是一无所获。
我是在控制器中发送进程通信消息的。 现在可以确定的是worker_num = 1的时候毫无问题，>1的时候就会偶尔报错。
暂时放弃折腾了，等大佬解答


PHP Fatal error:  Uncaught InvalidArgumentException: The app object has not been initialized in /www/wwwroot/air-combat.lingyier.com/aircombatservice/vendor/topthink/think-swoole/src/Sandbox.php:126
Stack trace:
#0 /www/wwwroot/air-combat.lingyier.com/aircombatservice/vendor/topthink/think-swoole/src/Sandbox.php(71): think\swoole\Sandbox->getApplication()
#1 /www/wwwroot/air-combat.lingyier.com/aircombatservice/vendor/topthink/framework/src/think/Container.php(74): think\swoole\Sandbox->think\swoole\{closure}()
#2 /www/wwwroot/air-combat.lingyier.com/aircombatservice/vendor/topthink/framework/src/helper.php(69): think\Container::getInstance()
#3 /www/wwwroot/air-combat.lingyier.com/aircombatservice/app/listen/swoole/OnMessage.php(49): app()
#4 [internal function]: app\listen\swoole\OnMessage->handle()
#5 /www/wwwroot/air-combat.lingyier.com/aircombatservice/vendor/topthink/framework/src/think/Container.php(333): ReflectionMethod->invokeArgs()
#6 /www/wwwroot/air-combat.lingyier.com/aircombatservice/vendor/topthink/framework/src/think/Container.php(366): think\Container->invokeMethod()
#7 /www/wwwroot/air-combat.lingyier.com/aircombatservice/vendor/topthink/framework/src/think/Event.php(288): think\Container->invoke()
#8 /www/wwwroot/air-combat.lingyier.com/aircombatservice/vendor/topthink/framework/src/think/Event.php(249): think\Event->dispatch()
#9 /www/wwwroot/air-combat.lingyier.com/aircombatservice/vendor/topthink/think-swoole/src/concerns/WithContainer.php(49): think\Event->trigger()
#10 /www/wwwroot/air-combat.lingyier.com/aircombatservice/vendor/topthink/think-swoole/src/ipc/driver/UnixSocket.php(24): think\swoole\Manager->triggerEvent()
#11 [internal function]: think\swoole\ipc\driver\UnixSocket->think\swoole\ipc\driver\{closure}()
#12 {main}
  thrown in /www/wwwroot/air-combat.lingyier.com/aircombatservice/vendor/topthink/think-swoole/src/Sandbox.php on line 126
PHP Fatal error:  Uncaught Swoole\Error: API must be called in the coroutine in /www/wwwroot/air-combat.lingyier.com/aircombatservice/vendor/topthink/framework/src/think/console/output/driver/Console.php:203
Stack trace:
#0 /www/wwwroot/air-combat.lingyier.com/aircombatservice/vendor/topthink/framework/src/think/console/output/driver/Console.php(203): proc_open()
#1 /www/wwwroot/air-combat.lingyier.com/aircombatservice/vendor/topthink/framework/src/think/console/output/driver/Console.php(180): think\console\output\driver\Console->getSttyColumns()
#2 /www/wwwroot/air-combat.lingyier.com/aircombatservice/vendor/topthink/framework/src/think/console/output/driver/Console.php(145): think\console\output\driver\Console->getTerminalDimensions()
#3 /www/wwwroot/air-combat.lingyier.com/aircombatservice/vendor/topthink/framework/src/think/console/output/driver/Console.php(82): think\console\output\driver\Console->getTerminalWidth()
#4 /www/wwwroot/air-combat.lingyier.com/aircombatservice/vendor/topthink/framework/src/think/console/Output.php(167): think\console\output\driver\Console->renderException()
#5 /www/wwwroot/air-combat.lingyier.com/aircombatservice/vendor/topthink/framework/src/think/exception/Handle.php(124): think\console\Output->renderException()
#6 /www/wwwroot/air-combat.lingyier.com/aircombatservice/vendor/topthink/framework/src/think/initializer/Error.php(57): think\exception\Handle->renderForConsole()
#7 /www/wwwroot/air-combat.lingyier.com/aircombatservice/vendor/topthink/framework/src/think/initializer/Error.php(94): think\initializer\Error->appException()
#8 [internal function]: think\initializer\Error->appShutdown()
#9 {main}
  thrown in /www/wwwroot/air-combat.lingyier.com/aircombatservice/vendor/topthink/framework/src/think/console/output/driver/Console.php on line 203

**Comment by yunwuxin** [comment]
~~~
class OnMessage {
	public function handle(Manager $manager,$event) {
              $manager->runInSandbox(function(GameManage $gameManage){
	              try{
			      dump(count($gameManage->sessionList));
		      }catch (\Exception $e){
			      dump($e->getMessage());
		      }
              });

	}
}
~~~

这样试试

**Comment by note-sun** [comment]
> ```
> class OnMessage {
> 	public function handle(Manager $manager,$event) {
>               $manager->runInSandbox(function(GameManage $gameManage){
> 	              try{
> 			      dump(count($gameManage->sessionList));
> 		      }catch (\Exception $e){
> 			      dump($e->getMessage());
> 		      }
>               });
> 
> 	}
> }
> ```
> 
> 这样试试

也有异常，我是在控制器中调用的方法发送进程消息，我的控制器是一个标准json返回，但是使用这个代码后，偶尔会在http请求响应这种，同时这html也会输出到控制台。 可以确定的是：如果不报错的时候，确实能正常获取到全局唯一的那个实例。
![image](https://github.com/user-attachments/assets/ffc468a1-8007-4bac-b7e3-93094a90f399)

![image](https://github.com/user-attachments/assets/480790b7-4cd2-4fd2-b2fe-b3d436c9d2e4)

**Comment by yunwuxin** [comment]
不知道你是在哪里注册的这个事件，这个事件是用于子进程之间通信的   需要在onWorkerStart之后注册

**Comment by note-sun** [comment]
我是在event.php文件中定义的这个事件处理类：
```php
'listen' => [
		'AppInit'  => [],
		'HttpRun'  => [],
		'HttpEnd'  => [],
		'LogLevel' => [],
		'LogWrite' => [],
		'swoole.message'   => [
			app\listen\swoole\OnMessage::class,
		],
	],
```

另外，我实在swoole.concretes里配置的我这个全局实例：

```php
//每个worker里需要预加载以共用的实例
	'concretes'  => [
		\app\service\globalInstances\GameManage::class
	],
```

看源码，发现好像也不存在顺序问题，pool.on(workerStart)的回调里订阅的ipc的onMessage，ipc的onMessage触发的swoole.message, 
![image](https://github.com/user-attachments/assets/9019ed03-b8c2-4989-b224-59721cba70d0)

**Comment by note-sun** [comment]
> ```
> class OnMessage {
> 	public function handle(Manager $manager,$event) {
>               $manager->runInSandbox(function(GameManage $gameManage){
> 	              try{
> 			      dump(count($gameManage->sessionList));
> 		      }catch (\Exception $e){
> 			      dump($e->getMessage());
> 		      }
>               });
> 
> 	}
> }
> ```
> 
> 这样试试

根据群主在qq群里的回复方案，在用协程容器包一层就可以了，完美搞定。最终就是在协程中运行沙箱环境，向沙箱环境注入所需要的全局实例即可。注意，我使用的是4.0.13版本

```php
public function handle($event, Manager $manager) {
		Coroutine::create(function () use ($event, $manager) {
				$manager->runInSandbox(function (GameManage $gameManage) {
					try {
						dump(count($gameManage->sessionList));
					} catch (\Exception $e) {
						dump($e->getMessage());
					}
				});
			});
	}
```
