### ISSUE TITLE
session组件有BUG

### ISSUE THREAD

**Issue by yumufeng** [top-think/think-swoole#39]
**BUG过程还原如下**

例如：
我们使用index/user/login 进行用户登录，登录后将用户一些信息存储到session中。此时我们会调用 Session::set() 进行用户的session设置。可以成功。

但是我们打开浏览器，清除cookie如下
![1](https://user-images.githubusercontent.com/9146937/46186363-c95cdf00-c310-11e8-99f7-5a3233a5e07f.png)

用户会退出登录，没有错。
但是我们再次去登录用户的时候，用户会登录不上，captcha验证码验证组件也会时效。原因在于，当我们用set去设置的时候，会判断是否有session_id存在，如下：
![2](https://user-images.githubusercontent.com/9146937/46186459-4a1bdb00-c311-11e8-858f-597dc051a045.png)

其中getId 如下：
`  /**
     * 获取session_id
     * @access public
     * @return string
     */
    public function getId()
    {
        return ThinkCookie::get($this->sessionName) ?: '';
    }
`
会去获取sessionId开头的 cookie，而此时的cookie已经被我们清空了。根本获取不到了id了

由于成员变量，在swoole里已初始化就加载内存中顶了

所以下面的这一段是不会再去执行了
`  
 empty($this->init) && $this->boot();

boot里面的
  if (false === $this->init) {
            $this->start();
        }
还有这个
if ($sessionId) {
            $this->setSession($sessionId, $name, $value);
  }
`
session设置就没有作用了

**Comment by yumufeng** [comment]
session 还有一个bug就是把session都存在了 $data 成员变量里面。这样会造成，这个数组越来越巨大，越来越吃内存。而且只要swoole启动了，用户没有主动退出去删除$data的键值对，这里面的数据会一直存在，换浏览器都不会消失。

**Comment by liu21st** [comment]
已经改进了 感谢反馈
