### ISSUE TITLE
自定义服务类出现错误：Swoole\Server::on(): unknown event types[Message]

### ISSUE THREAD

**Issue by peijiyang0811** [top-think/think-swoole#40]
<?php
/**
 * Created by PhpStorm.
 * User: admin
 * Date: 2018/10/10
 * Time: 14:36
 */

namespace app\http;
use think\swoole\Server;

class Swoole extends Server
{
    protected $host = '0.0.0.0';
    protected $port = 9502;
    protected $option = [
        'worker_num'            => 4,
        'daemonize'	            => false,
        'task_worker_num'       => 4
        //'backlog'	=> 128
    ];

    public function onMessage($server, $frame)
    {
        echo "receive from {$frame->fd}:{$frame->data},opcode:{$frame->opcode},fin:{$frame->finish}\n";
        $server->push($frame->fd, "this is server");
    }
    // 设置了onRequest回调，websocket服务器也可以同时作为http服务器
    public function onRequest($request, $response)
    {
        $response->end("<h1>Hello Swoole. #this is socket server"  . "</h1>");
    }
    
    public function onTask($server, $task_id, $worker_id, $data)
    {
        echo 'task start success,taskID is '.$task_id.PHP_EOL;
        sleep(10);
        return ['code'=>0, 'message'=>'OK'];// 返回到 onFinish 中
    }
    public function onFinish($server, $task_id, $data)
    {
        echo 'taskId is '.$task_id . PHP_EOL;
        echo 'task coming data is '. json_encode($data);
        echo 'task finished....'.PHP_EOL;
    }
    public function onClose($server, $fd)
    {
        echo "client {$fd} closed\n";
    }
}

所有回调事件都 在自定义服务里面洗的话，就报这个错误，，unknown event types[XXXX]

**Comment by xavieryang007** [comment]
这个是设置swoole回调有问题，你代码格式有些问题，最好可以吧代码格式化一下
