### ISSUE TITLE
think-swoole重启是否应该适当延时？

### ISSUE THREAD

**Issue by DarkiT** [top-think/think-swoole#47]
现在的代码没有增加延时，重启有很大几率出现端口绑定冲突问题，错误代码如下：
`[root@NAS sms]# php think swoole:server restart
Stopping swoole server...
> success
Starting swoole server...
[2018-11-10 12:59:15 @28949.0]	WARNING	swSocket_bind (ERROR 502): bind(127.0.0.1:65535) failed. Error: Address already in use [98]

                                                                                     
  [Swoole\Exception]                                                                 
  failed to listen server port[127.0.0.1:65535]. Error: Address already in use[98].  
                                                                                     

`
当对重启指令部分适当增加点延时后，重启不会提示端口绑定失败。
`/**
     * 重启server
     * @access protected
     * @return void
     */
    protected function restart()
    {
        $pid = $this->getMasterPid();

        if ($this->isRunning($pid)) {
            $this->stop();
        }
        sleep(1);
        $this->start();
    }`
执行结果如下：
`[root@NAS sms]# php think swoole:server restart
Stopping swoole server...
> success
Starting swoole server...
[root@NAS sms]#`

**Comment by xavieryang007** [comment]
服务是否负载相对较高？服务器是否配置较低？出现这种问题是服务没有完全关闭造成。希望可以描述下出现问题的场景

**Comment by DarkiT** [comment]
我发现真不是服务器配置的问题，我换了一台高配置的服务器也是这样子，去swoole群里问了，也是建议适当延时一下等待所有进程关闭后再启动程序，另外还发了一个问题，根据官方收藏使用了自定义的服务类后重启、重载、停止都会提示程序没用运行，实质上程序是运行了的。
![qq 20181113191148](https://user-images.githubusercontent.com/608092/48409880-0291c700-e778-11e8-90cd-c8c16750f5a3.png)
查看源码发现是在pid_file文件后跟了一个端口号，导致了找不到pid文件造成的，说明一下我是自定义了一个异步的Websocket服务，所以配置文件里面的那些参数均不生效了，得自己重新定义。但是自己定义了就会出现上述问题。

**Comment by xavieryang007** [comment]
如果自己实现的server，可以自行实现重启方法

**Comment by xavieryang007** [comment]
可以参考Http.php
