### ISSUE TITLE
 使用think-swoole 获取 websocket实例，发送消息的时候报错

### ISSUE THREAD

**Issue by DioBrandoLong** [top-think/think-swoole#48]
![5 owpcwdsfgw 8 b8y baew](https://user-images.githubusercontent.com/27342144/48397093-a159fb80-e757-11e8-8101-641da00894e2.png)
![s 22k u_7 bw w4t 013 f](https://user-images.githubusercontent.com/27342144/48397100-a454ec00-e757-11e8-90a3-697350c38a89.png)
根据提示是 server获取为空了

**Comment by xavieryang007** [comment]
是否为异步发送

**Comment by DioBrandoLong** [comment]
我实在控制器里直接发送的， 是因为这个原因么？

**Comment by xavieryang007** [comment]
你是HTTP模式下直接发送的？那样是不行的。
原因：
  websocket模式下才会获取到websocket请求的fd，也就是连接ID序列，HTTP模式下需要指定发给谁。也就是A通过websocket方式连接到S服务器，那么S当A发数据给S后，S处理完数据反馈默认是直接反馈给A的，而HTTP下，压根不知道当前谁连接的websocket

**Comment by DioBrandoLong** [comment]
哦。 我以为通过swoole_server.php文件 开启的就是websocket服务， 我的命令用的也是 
php think swoole:server -d， 我这个配置是不是不对啊
![ua3jus p89 5 cu6 b6wp27](https://user-images.githubusercontent.com/27342144/48398057-aff5e200-e75a-11e8-971b-76ba24de4c29.png)
![c x ndj qzju5z hv9m w1](https://user-images.githubusercontent.com/27342144/48398062-b2f0d280-e75a-11e8-9c30-27127d82adf6.png)

**Comment by xavieryang007** [comment]
不是这样  默认启动php think swoole 
![image](https://user-images.githubusercontent.com/6174650/48398179-06632080-e75b-11e8-9832-3fa2d0f74c92.png)
上图所指位置设置为websocket即可

**Comment by DioBrandoLong** [comment]
大佬 我根据你的提示 修改了swoole.php文件，并且创建了一个 task 来发消息，不过还是报错了。。。
![0i2p 7 dj02yoe3e fwi8n](https://user-images.githubusercontent.com/27342144/48399106-aae66200-e75d-11e8-96bc-086351eb687b.png)
![pg hah9q s9raw zx zq3q](https://user-images.githubusercontent.com/27342144/48399118-b3d73380-e75d-11e8-9cde-e47528e0bdb2.png)
![3az hq ivwthnzp j4mja3](https://user-images.githubusercontent.com/27342144/48399122-b6d22400-e75d-11e8-8d99-593b226bfc2b.png)
![h5b4d e0b mf3c lm5jczxp](https://user-images.githubusercontent.com/27342144/48399128-b9cd1480-e75d-11e8-8da5-403d1e194aa2.png)

**Comment by xavieryang007** [comment]
Websocket模式下不要HTTP访问，Task模式下现在需要自己实现websocket发送。你上面的错误是HTTP模式访问的，你需要先了解websocket和HTTP

**Comment by xavieryang007** [comment]
你现在是两个概念混淆了

**Comment by DioBrandoLong** [comment]
swoole.php 的socket_type 不是可以决定当前是 什么模式么？既然我指定了websocket 还能变成http请求。。。我现在 就想在控制器里用 websocket发送消息 要怎么写啊，虽然很无耻但能给点代码示例嘛。。。我是真的找不到别的资料了

**Comment by xavieryang007** [comment]
你需要看下swoole文档，websocket是继承于Http模式的，也就是websocket包含HTTP的所有功能。
从协议来讲websocket认证是发送的HTTP请求，所以websocket服务都是具有HTTP功能的

**Comment by xavieryang007** [comment]
```
{
    "event":"",//事件名称
    "url":"",//目标地址
    "arguments":{//客户端投递数据
        "post":[],//post数据
        "get":[],//get数据
        "cookie":[],//cookie数据
   }
}
```

采用上述结构，通过websocket方式发送数据包给服务就会触发指定控制器，如下代码就可以回复数据
use think\swoole\WebSocketFrame;

$client=WebSocketFrame::getInstance();
//发送数据给当前请求的客户端
$client->pushToClient([]);

**Comment by DioBrandoLong** [comment]
额。。。。。好吧，后期能把这个think-swoole 分两种模式嘛， 一种http 一种 websoket。

**Comment by xavieryang007** [comment]
可以配置的

**Comment by xavieryang007** [comment]
open_http_protocol
启用Http协议处理，Swoole\Http\Server会自动启用此选项。设置为false表示关闭Http协议处理  

https://wiki.swoole.com/wiki/page/635.html

**Comment by DioBrandoLong** [comment]
服务端发送数据

use think\swoole\WebSocketFrame;

$client=WebSocketFrame::getInstance();
//发送给所有客户端
$client->pushToClients([]);//参数为数组，字符串，数字
pushToClients 这个方法里边的数据结构有要求嘛？

**Comment by xavieryang007** [comment]
参数是数组就可以了

**Comment by DioBrandoLong** [comment]
现在问题是，主要问题在发送消息上 我在控制器里直接创建 WebSocketFrame 的实例就报错了
  $client=WebSocketFrame::getInstance(); 这行代码直接报错了

**Comment by DioBrandoLong** [comment]
如果我开一个 task 就报 swoole类不存在的错。。。

**Comment by DioBrandoLong** [comment]
> 你是HTTP模式下直接发送的？那样是不行的。
> 原因：
> websocket模式下才会获取到websocket请求的fd，也就是连接ID序列，HTTP模式下需要指定发给谁。也就是A通过websocket方式连接到S服务器，那么S当A发数据给S后，S处理完数据反馈默认是直接反馈给A的，而HTTP下，压根不知道当前谁连接的websocket

我现在懂你说的意思了，我这边设定了一个端口6666访问这个端口会被nginx重定向到 websocket 
所以我现在的访问 URL就是  http:www.mywebsocket.com:6666/send . 这个 send我通过路由 指向了控制器的一个方法，我在那个方法中开启 task ，task的 run方法中 向所有客户端发送消息了, 但是他报了个错 swoole不存在啊。。。

**Comment by xavieryang007** [comment]
Task 里不能直接采用websocketframe这个类发送，需要重新初始化，这个也是我前几天在做项目的时候发现的，因为server不能被序列化，所以就会提示找不到server，不过可以曲线救国
容器里有server，可以通过如下获取
```
$swoole=app("swoole");
$swoole->push($fd,$data);
```
在task里用上面方法发送，下次更新会修复这个问题

**Comment by DioBrandoLong** [comment]
> Task 里不能直接采用websocketframe这个类发送，需要重新初始化，这个也是我前几天在做项目的时候发现的，因为server不能被序列化，所以就会提示找不到server，不过可以曲线救国
> 容器里有server，可以通过如下获取
> 
> ```
> $swoole=app("swoole");
> $swoole->push($fd,$data);
> ```
> 在task里用上面方法发送，下次更新会修复这个问题

好的 写了， 话说现在支持 WSS嘛，能否再曲线救国下。。。

**Comment by xavieryang007** [comment]
我一般都直接让swoole采用ssl，习惯前面采用代理，比如nginx，反向代理的话只需要nginx支持就可以了
，后面的服务不需要支持

**Comment by DioBrandoLong** [comment]
> 我一般都直接让swoole采用ssl，习惯前面采用代理，比如nginx，反向代理的话只需要nginx支持就可以了
> ，后面的服务不需要支持

能请教下 关于前端界面用ajax请求控制器的方法时的一个问题么。 我的想法就是 Ip+6666直接访问到 websocket 。这个是可以的。但是 如果我  Ip+6666+send  就是说想在websocket下指向控制器的方法就不行了。  就是说 要怎么做才能让前端 访问到 websocket下 的 控制器的方法呢

**Comment by xavieryang007** [comment]
不建议这样做，因为websocket和HTTP模式返回数据模式不同，如果那样做需要做一些兼容。
websocket模式下，是可以访问任意控制器的，访问方式为“/分组/控制器名/方法名”

**Comment by DioBrandoLong** [comment]
> 不建议这样做，因为websocket和HTTP模式返回数据模式不同，如果那样做需要做一些兼容。
> websocket模式下，是可以访问任意控制器的，访问方式为“/分组/控制器名/方法名”

能给点代码或者DEMO嘛。。。。

**Comment by singwa0725** [comment]
我也是遇到这个问题，请问大佬，怎样解决呢
