### ISSUE TITLE
请问下  这个如果是在https下开启 wss 要如何配置呢 

### ISSUE THREAD

**Issue by DioBrandoLong** [top-think/think-swoole#49]
没找到 SSL的配置啊

**Comment by xavieryang007** [comment]
可以采用nginx反向代理

**Comment by DioBrandoLong** [comment]
![9h 1yd ftq oqjxrtkq0 w](https://user-images.githubusercontent.com/27342144/48670302-908ef880-eb50-11e8-98ef-a808a99f6872.png)
应该不行的。 https模式下 ws被强制换成 wss了
这个界面现在有没有添加 SSL HTTPS的配置啊
![to6y3 t0q1ul4k0op 1 y](https://user-images.githubusercontent.com/27342144/48670322-db107500-eb50-11e8-9cc8-c3dfdbd77ff1.png)

**Comment by jun3372** [comment]
NGINX端口代理
    location ^~ /websocket/8087 {
        proxy_pass http://127.0.0.1:8087;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";
    }
