### ISSUE TITLE
使用队列报错：没有这个xavier\swoole\Task类文件

### ISSUE THREAD

**Issue by fffloong** [top-think/think-swoole#50]
use xavier\swoole\Task as SwooleTask;

`Error: Class 'xavier\swoole\Task' not found in /home/wwwroot/tp5/vendor/topthink/think-swoole/src/queue/Task.php:60`

**Comment by xavieryang007** [comment]
需要修改为use think\swoole\facade\Task as SwooleTask;

**Comment by fffloong** [comment]
谢谢，看Task.php下的SwooleTask::async() 是静态调用，是不是应该把think\swoole\Task下的方法也改为public static function async()

**Comment by xavieryang007** [comment]
use think\swoole\facade\Task as SwooleTask; 不好意思 应该修改为这个

**Comment by fffloong** [comment]
emmm.... 还是 use think\facade\Task as SwooleTask; 这个吧，可以用，user think\facade\Task 就Not Found 了

**Comment by xavieryang007** [comment]
use think\swoole\facade\Task as SwooleTask;可以找到

**Comment by fffloong** [comment]
嗯嗯，辛苦！刚才少了一级swoole；
已经无错跑起来了，我看队列这里在swoole.php配置好然后启动，程序就自动按照配置消费了队列，是这样吗？

**Comment by xavieryang007** [comment]
是的 ，可以在队列打印，然后你就可以看到哪个队列在消耗。

**Comment by fffloong** [comment]
swoole task queue  调用think-queue，在里面的sleep会有什么影响吗？

**Comment by xavieryang007** [comment]
process模式不会有影响，task模式会有影响。

**Comment by xavieryang007** [comment]
TASK模式是基于swoole_task_worker的，这个是共用的异步执行worker，如果他睡眠了，影响所有任务的执行

**Comment by fffloong** [comment]
异步任务投递后，任务执行是process模式还是task模式？

**Comment by xavieryang007** [comment]
异步任务投递是task模式
