### ISSUE TITLE
swoole 模式下控制器中的$this->request  和 直接获取 request() 获取的数据不一样

### ISSUE THREAD

**Issue by w-s-hu** [top-think/think-swoole#53]
swoole 模式下控制器中的$this->request  和 直接获取 request() 获取的数据不一样
![image](https://user-images.githubusercontent.com/45419599/49197642-91cee980-f3ca-11e8-91ca-cb42df1af280.png)
![image](https://user-images.githubusercontent.com/45419599/49197657-9eebd880-f3ca-11e8-8bb1-ebcfcfcf0f07.png)
在页面中提交一次ajax post 请求，一会不论怎么刷新页面  一直是post
还有一个问题  swoole 中ajax 标识是 x-requested-with  系统获取是 HTTP_X_REQUESTED_WITH 所有ajax判断也是失败

**Comment by xavieryang007** [comment]
暂时可以优先用request()  稍后会修复这个。

**Comment by lnlion** [comment]
遇到和上面完全一样的问题； 在swoole模式下，`$this->request` 这个变量貌似会被缓存； 以及遇到同样的$this->request->isAjax() 判断无效的问题；
