### ISSUE TITLE
request中当前语言为空

### ISSUE THREAD

**Issue by thinkcmf** [top-think/think-swoole#60]

**Comment by yumufeng** [comment]
大佬，swoole是常住内存框架，所以设置了 max_request后，构造函数里只执行一次。等到下次worker重启后再初始化：https://wiki.swoole.com/wiki/page/p-max_request.html

目前Tp如果继承自Controller的话，通过$this->request 是只能获取一次值的

需要 通过action里依赖注入的方式获取request。

**Comment by liu21st** [comment]
最新版本的核心框架已经改进过支持了 等下一个版本发布就好了
