### ISSUE TITLE
swoole 和swoole:server 有什么区别?

### ISSUE THREAD

**Issue by buffge** [top-think/think-swoole#69]
我看源码,如果是swoole 启动就会使用自定义的think\swoole\Application; 
此时可以启用Websocket服务也可以启用Http服务. 但是如果是swoole:server启动就不使用think\swoole\Application; 
问题
1: 请问这两种启动方式的区别是什么?
2: 为什么swoole:server方式启动 不使用think\swoole\Application,而swoole却使用了;
3. 当使用swoole 方式启动Websocket服务时,返回消息是$resp->send(),Websocket 发送消息不应该是 $server->push($frame->fd,$resp->getData())吗?

**Comment by liu21st** [comment]
参考：https://www.kancloud.cn/thinkphp/think-swoole/content
