### ISSUE TITLE
异步任务提示“类不存在: swoole”

### ISSUE THREAD

**Issue by daironghua521** [top-think/think-swoole#73]
调用异步任务投递提示“类不存在: swoole”
![1](https://user-images.githubusercontent.com/23692605/54079963-6c367200-4321-11e9-91f3-0a99c66909a9.png)

**Comment by sincez** [comment]
同求

**Comment by xavieryang007** [comment]
自定义还是启动的php think swoole

**Comment by sincez** [comment]
我这是自定义

**Comment by xavieryang007** [comment]
自定义不支持，需要自己参考代码进行初始化

**Comment by sincez** [comment]
那知道了，感谢

**Comment by lingkong5104** [comment]
你好，我是使用php think swoole 启动的，在控制器中添加任务。还是会报或者错误，这是什么原因？
