### ISSUE TITLE
在mac中启动swoole时swoole_set_process_name的兼容问题

### ISSUE THREAD

**Issue by toncii** [top-think/think-swoole#81]
$ php think swoole start
Starting swoole http server...
PHP Fatal error:  Uncaught think\exception\ErrorException: swoole_set_process_name(): swoole_set_process_name is not supported on MacOS

**Comment by xavieryang007** [comment]
mac 下swoole 不支持这个

**Comment by toncii** [comment]
我的解决方法是在此方法前加一个‘@‘，之后就能正常启动服务
@swoole_set_process_name($name);
