### ISSUE TITLE
swoole HTTP server 跨域问题

### ISSUE THREAD

**Issue by littlezo** [top-think/think-swoole#82]
swoole HTTP server 模式下 跨域请求报错404 经多少google得来结果 
修改: /vendor/topthink/think-swoole/src/Http.php

public function onRequest(\swoole_http_request $request, \swoole_http_response $response)
    {
        //$response->header('Access-Control-Allow-Origin', '*');
        $response->header('Access-Control-Allow-Origin', $request->header['origin'] ?? '');
        $response->header('Access-Control-Allow-Methods', 'OPTIONS');
        $response->header('Access-Control-Allow-Headers', 'x-requested-with,session_id,Content-Type,token,Origin');
        $response->header('Access-Control-Max-Age', '86400');
        $response->header('Access-Control-Allow-Credentials', 'true');

        if ($request->server['request_method'] == 'OPTIONS') {
            $response->status(200);
            $response->end();
            return;
        };

        // 执行应用并响应
        $this->app->swoole($request, $response);
    }

还望官方修复

**Comment by liu21st** [comment]
这个其实使用框架的跨域请求支持就行 核心有修正过
