### ISSUE TITLE
异步task中出现协成就会报错

### ISSUE THREAD

**Issue by zsboss** [top-think/think-swoole#96]
异步task中出现协成就会报错，然后根据官方 设置了task_enable_coroutine = true，然后整个异步任务会报错  	WARNING	swManager_check_exit_status: worker#4[pid=76680] abnormal exit, status=255, signal=0

**Comment by jeristiano** [comment]
异步任务最好不要开启协程,整个think-swoole扩展最好不要使用协程方式,因为thinkphp框架中使用了很多静态属性 这样在长生命周期swoole里可能会影响到协程的调度

**Comment by zsboss** [comment]
谢谢大佬的解答
