### ISSUE TITLE
Rpc 例子

### ISSUE THREAD

**Issue by edenleung** [top-think/think-swoole#99]
看到有人要Rpc例子 #97 #98 ，研究了下。

***Swoole.php下的client 现在还是不知道怎么使用, 会的可以分享下。***

https://www.xiaodim.com/2019/10/25/thinkphp6-rpc-tutorial

大概这样使用？ 

建议
* 后期是否可以利用注解方式快速注册Service

## 安装
```
composer require topthink/think-swoole
```

### 接口
```php
<?php
namespace app\service;

interface OperationInterface
{
    /**
     * 加法运算
     *
     * @param [type] $a
     * @param [type] $b
     * @return void
     */
    public function add($a, $b);
}
```

## 定义服务提供者
```php
<?php

namespace app\service;

/**
 * 这是个运算服务
 * 
 */
class OperationService implements OperationInterface
{
    /**
     * 执行加法运算
     *
     * @param [type] $a
     * @param [type] $b
     * @return void
     */
    public function add($a, $b)
    {
        return $a + $b;
    }
}
```

## 配置

`swoole.php`

```
'rpc'        => [
    'server' => [
        'enable'   => true,
        'port'     => 9000,
        'services' => [
            'OperationService' => \app\service\OperationService::class 
        ],
    ],
'client' => [
       'OperationService' => ['host' => 'http://localhost', 'port'=> 9000,'timeout' => 2.5],
    ]
],
```
## 生成rpc 接口配置
```php
php think rpc:interface
```
## 调用
```php
<?php

namespace app\controller;

use app\BaseController;
use rpc\contract\OperationService\OperationInterface;

/**
 * @package app\controllers
 * 
 */
class Index extends BaseController
{
    
    public function index(OperationInterface $service)
    {
        $res = $service->add([1, 3]);
        var_dump($res);
    }
}
```

## 启动
```sh
php think swoole
```

访问 http://localhost
```
// 结果
`int(4)`
```

**Comment by porsion** [comment]
你这个New client('xxx',9000)根本 就不对，需要先app::make('interface'),然后interface里需要const interface = RPC.
另外，你的result是自己手动组装的，这个绝不是官方推荐的办法。
我一直研究，实际上，官方应该是设计的，先拿到 think\swoole\app,然后make 你的interface，然后返回临时生成的implements server.php，然后调用临时生成的server.php里相应的方法，最后调用$this->proxyCall()返回数据

**Comment by shuipf** [comment]
你这个用法有点不对~~
需要再rpc客户端执行 php think rpc:interface 
然后再客户端调用rpc服务端接口，直接利用框架的依赖注入进行调用~~
具体的rpc调用实现，作者已经通过 App 这个类的 make进行处理了~~所以我们用的时候，只要和正常的类调用一样。

注意：客户端rpc的client要配置
![image](https://user-images.githubusercontent.com/2285144/67549007-d88da680-f735-11e9-8549-c43158b6b216.png)

**Comment by xiaodit** [comment]
> 客户端rpc的client要配置
我有执行 php think rpc:interface
rpc.php 不啥东西

**Comment by edenleung** [comment]
> 你这个用法有点不对~~
> 需要再rpc客户端执行 php think rpc:interface
> 然后再客户端调用rpc服务端接口，直接利用框架的依赖注入进行调用~~
> 具体的rpc调用实现，作者已经通过 App 这个类的 make进行处理了~~所以我们用的时候，只要和正常的类调用一样。
> 
> 注意：客户端rpc的client要配置
> ![image](https://user-images.githubusercontent.com/2285144/67549007-d88da680-f735-11e9-8549-c43158b6b216.png)

我有执行 php think rpc:interface
rpc.php 没发现有啥东西

**Comment by shuipf** [comment]
你要在客户端执行，客户端要配置 client 。rpc.php就会有东西的

**Comment by edenleung** [comment]
谢谢 知道怎么用了
```
public function index(OperationService $service)
    {
        var_dump($service->add(1, 3));
    }
```

**Comment by edenleung** [comment]
> 你要在客户端执行，客户端要配置 client 。rpc.php就会有东西的

可以发点client的配置参考吗

**Comment by porsion** [comment]
`'rpc'        => [
        'server' => [
            'enable'   => false,
            'port'     => 9000,
            'parser'   => JsonParser::class,
            'services' => [
            ],
        ],
        
        // 命令行使用方式 rpc:interface 之后，将会尝试链接下面的所有服务器，成功后将下面服务器上所有的rpcServer.php 下载到本地
        // 并将之写成interface文件，空间名为：rpc\contract\xxx
        'client' => [
           'user'       => ['host' => '127.0.0.1', 'port'=> 8080,'timeout' => 2.5],
           'log'       => ['host' => '127.0.0.1', 'port'=> 8080,'timeout' => 2.5],
           'msg'       => ['host' => '127.0.0.1', 'port'=> 8080,'timeout' => 2.5],

        ],`

config/swoole.php
